### ISSUE TITLE
Feature request: nbdev_conda option to create environment.yml

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#1008]
There is already an exported function `write_conda_meta(path='conda')` that could be used for that.

Raison d'être: 

* Big projects have lots of dependencies
* Those dependencies need to be tested on GitHub workflows
* Getting lots of dependency packages is much faster via conda/mamba on GH workflows
* Caching packages and/or environment makes it even faster and saves a lot of bandwidth
* Existing solutions for caching require an `environment.yml`
* Requirements should only be listed once, currently in settings.ini
* Hence a small CLI tool to reliably create `environment.yml` from settings.ini would be very handy for GH workflows.

Anticipated CLI syntax:

`nbdev_conda --write_env_yml` or similar.

**Comment by ez2rok** [comment]
I was looking for something exactly like this!

Perhaps it would be interesting to also have a command that does the reverse: the command takes a `requirements.yml` file and populates the requirements part of the `settings.ini` file. This would be helpful for users that wrote their nbdev package in a conda environment where it might be time consuming or complicated to write all the packages in the requirements section of the `settings.ini` file.

**Comment by jph00** [comment]
I believe that `nbdev_conda --do_build false --skip_upload` should do this, assuming that the pypi package is available.

**Comment by michaelaye** [comment]
IIUC, for the creation of the pypi package one needs to "run" the installer right? Which would try to drag in all dependencies via pip, which precludes the premise of this feature request, to be able to get the majority of all dependencies in via a cached conda env.

**Comment by michaelaye** [comment]
ah, no, that's why you put `--do_build false` of course.
However:

```bash
…/nbplanetary2 ❯ nbdev_conda --do_build false --skip_upload
Traceback (most recent call last):
  File "/home/ayek72/mambaforge/envs/py310/bin/nbdev_conda", line 8, in <module>
    sys.exit(release_conda())
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 262, in release_conda
    write_conda_meta(path)
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 238, in write_conda_meta
    _write_yaml(path, *_get_conda_meta())
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 207, in _get_conda_meta
    pypi = pypi_json(f'{name}/{ver}')
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 151, in pypi_json
    return urljson(f'{_PYPI_URL}{s}/json')
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/net.py", line 125, in urljson
    res = urlread(url, data=data, timeout=timeout)
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/net.py", line 115, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
```

**Comment by michaelaye** [comment]
Here's a little gist that does what I need:

https://gist.github.com/michaelaye/6670f8604c7ada429e56210b15bdc4b7

I just put it into my root folder for now.

**Comment by jph00** [comment]
The pypi installer has to exist for the current version. Your error suggests it doesn't exist.
