### ISSUE TITLE
nbdev_release_gh error upon closing CHANGELOG

### ISSUE THREAD

**Issue by rossheat** [fastai/nbdev#1031]
After running `nbdev_release_gh` and closing CHANGELOG.md, I get the following error: 

```
Make release now? (y/n) y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/nbdev_release_gh", line 8, in <module>
    sys.exit(release_gh())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbdev/release.py", line 128, in release_gh
    ver = Release(token=token).release()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbdev/release.py", line 85, in release
    self.gh.create_release(ver, branch=self.cfg.branch, body=notes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ghapi/core.py", line 176, in create_release
    rel = self.repos.create_release(tag_name, target_commitish=branch, name=name, body=body,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ghapi/core.py", line 61, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ghapi/core.py", line 111, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fastcore/net.py", line 214, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fastcore/net.py", line 115, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None

```

I get the same error when running `nbdev_release_gh --token <MY_GITHUB_TOKEN>`

I have a GitHub personal access token in both a file named 'token' in the root of my nbdev project and exported as an environment variable named `GITHUB_TOKEN`, which I've confirmed is available via `os.getenv("GITHUB_TOKEN")` 

I am able to successfully create releases using that exact GitHub personal access token via a cURL request in the following format: 
```
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \ 
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/repos/OWNER/REPO/releases \
  -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
```
as detailed in the GitHub [release docs](https://docs.github.com/en/rest/releases/releases#create-a-release).

The environment variable was set at the time when I ran `nbdev_new` to create the project, hence I received no warning message. 

That my repository (which is private) was able to be read in order to generate the CHANGELOG, suggests that the issue is not with my token. 

I have tried with both public and private repositories.

Possibly similar to #907

nbdev: 2.2.10
fastrelease: 1.5.26
python 3.10.4
os: macOS Monterey 12.2.1

**Comment by rossheat** [comment]
FIXED: I updated the value of `branch` in `settings.ini` from `master` to `main`.
