### ISSUE TITLE
nbdev_release_gh | 400 <= e.code < 500: raise ExceptionsHTTP

### ISSUE THREAD

**Issue by lgonzalezsa** [fastai/nbdev#1082]
Trying to create a release with `nbdev_release_gh` but got:

```bash
export GHAPI_DEBUG=1
nbdev_release_gh
{'data': None,
 'full_url': 'https://github.enterprise.com/api/v3/repos/enterprise/the_repo/releases/latest',
 'headers': {'Accept': 'application/vnd.github.v3+json'},
 'method': 'GET'}
{'data': None,
 'full_url': 'https://github.enterprise.com/api/v3/repos/enterprise/the_repo/issues?state=closed&labels=breaking&sort=created&since=2000-01-01T00%3A00%3A004Z',
 'headers': {'Accept': 'application/vnd.github.v3+json'},
 'method': 'GET'}
{'data': None,
 'full_url': 'https://github.enterprise.com/api/v3/repos/enterprise/the_repo/issues?state=closed&labels=enhancement&sort=created&since=2000-01-01T00%3A00%3A004Z',
 'headers': {'Accept': 'application/vnd.github.v3+json'},
 'method': 'GET'}
{'data': None,
 'full_url': 'https://github.enterprise.com/api/v3/repos/enterprise/the_repo/issues?state=closed&labels=bug&sort=created&since=2000-01-01T00%3A00%3A004Z',
 'headers': {'Accept': 'application/vnd.github.v3+json'},
 'method': 'GET'}
Make release now? (y/n) y
{'data': b'{"tag_name": "1.0.1", "target_commitish": "master", "name": "v1.0.1"'
         b', "body": "", "draft": false, "prerelease": false}',
 'full_url': 'https://github.enterprise.com/api/v3/repos/enterprise/the_repo/releases',
 'headers': {'Accept': 'application/vnd.github.v3+json'},
 'method': 'POST'}
Traceback (most recent call last):
  File "/home/gonluisr/miniconda3/envs/dev_env/bin/nbdev_release_gh", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_release_gh')())
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/gonluisr/github/nbdev/nbdev/release.py", line 132, in release_gh
    ver = Release(token=token).release()
  File "/home/gonluisr/github/nbdev/nbdev/release.py", line 89, in release
    self.gh.create_release(ver, branch=self.cfg.branch, body=notes)
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/ghapi/core.py", line 180, in create_release
    rel = self.repos.create_release(tag_name, target_commitish=branch, name=name, body=body,
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/ghapi/core.py", line 61, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/ghapi/core.py", line 120, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/fastcore/net.py", line 217, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/home/gonluisr/miniconda3/envs/dev_env/lib/python3.10/site-packages/fastcore/net.py", line 118, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None

```

**Comment by jph00** [comment]
The latest master version of ghapi and fastcore should give more info on this error.

Perhaps your default branch isn't called "master". If so, you need to update it settings.ini. Or perhaps your token doesn't have access? If you still have issues, please ask for help on forums.fast.ai.

**Comment by lgonzalezsa** [comment]
You were right, the default branch is called main not master, after changing settings.ini all set.
You all in fastai rules! nbdev is awesome!

**Comment by jph00** [comment]
Glad you got it sorted!
