### ISSUE TITLE
Problem migrating to nbdev2 with final nbdev_preview command 

### ISSUE THREAD

**Issue by ChrisRichardMiles** [fastai/nbdev#1110]
I run nbdev_preview and I get an error with a stack trace that ends with this: 
```
Exception: Error in notebook: Core in cell 42 :
#|output: asis
#| echo: false
show_doc(load_features)
```
I'm not sure why. the cell I have in `core` only has the `show_doc(load_features)`
I even tried deleting this cell and rerunning nbdev_export and nbdev_preview but I keep getting the same stack trace. Is there some cache or something I need to delete? I have tried deleting _proc before rerunning nbdev_preview. 

I would really appreciate some help from anyone. Thank you. 

full stack trace if its needed: 

```
NB: From v1.2 `_quarto.yml` is no longer auto-updated. Please remove the `custom_quarto_yml` line from `settings.ini`
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/c/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-ac392df88f5c>", line 3, in <cell line: 3>
    show_doc(load_features)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/showdoc.py", line 191, in show_doc
    else:return renderer(sym or show_doc, name=name, title_level=title_level)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/showdoc.py", line 127, in __init__
    try: self.sig = signature_ex(sym, eval_str=True)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 350, in signature_ex
    ann = type_hints(obj)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 318, in type_hints
    return {k:_eval_type(v,glb,loc) for k,v in ann.items()}
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 318, in <dictcomp>
    return {k:_eval_type(v,glb,loc) for k,v in ann.items()}
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 311, in _eval_type
    res = eval_type(t, glb, loc)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 305, in eval_type
    return eval(t, glb, loc)
  File "<string>", line 1
    list like
         ^
SyntaxError: unexpected EOF while parsing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/parallel.py", line 46, in _call
    return g(item)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/serve_drv.py", line 22, in main
    if src.suffix=='.ipynb': exec_nb(src, dst, x)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/serve_drv.py", line 16, in exec_nb
    cb()(nb)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/processors.py", line 221, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/process.py", line 119, in _proc
    for cell in self.nb.cells: self._process_cell(proc, cell)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/process.py", line 110, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/processors.py", line 201, in __call__
    raise Exception(f"Error{' in notebook: '+title if title else ''} in cell {cell.idx_} :\n{cell.source}") from self.k.exc[1]
Exception: Error in notebook: Core in cell 42 :
#|output: asis
#| echo: false
show_doc(load_features)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/c/miniconda3/bin/nbdev_preview", line 8, in <module>
    sys.exit(nbdev_preview())
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/quarto.py", line 271, in nbdev_preview
    cache,cfg,path = _pre_docs(path, n_workers=n_workers, **kwargs)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/quarto.py", line 175, in _pre_docs
    cache = proc_nbs(path, n_workers=n_workers, **kwargs)
  File "/home/c/miniconda3/lib/python3.9/site-packages/nbdev/serve.py", line 76, in proc_nbs
    parallel(nbdev.serve_drv.main, files, n_workers=n_workers, pause=0.01, **kw)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/parallel.py", line 117, in parallel
    return L(r)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/foundation.py", line 98, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/foundation.py", line 106, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/basics.py", line 66, in listify
    elif is_iter(o): res = list(o)
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/c/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
Exception: Error in notebook: Core in cell 42 :
#|output: asis
#| echo: false
show_doc(load_features)

**Comment by seeM** [comment]
I think it's evaluating the type annotations of `load_features`, one of which is the string `list like`, which isn't a valid type.

(This is somewhat related to #1116.)

**Comment by ChrisRichardMiles** [comment]
> I think it's evaluating the type annotations of `load_features`, one of which is the string `list like`, which isn't a valid type.
> 
> (This is somewhat related to #1116.)

Thank you very much. That was the issue.
