### ISSUE TITLE
running `nbdev_preview` gives a `KeyError: 'state'`

### ISSUE THREAD

**Issue by deven-gqc** [fastai/nbdev#1127]
Versions:
`nbdev` 2.3.7
`fastcore`: 1.5.27
`execnb`: 0.1.4

All notebooks have this as the first cell
```
# title
> description
- skip_exec: true
```

Running `nbdev_preview` gives a `KeyError: 'state'`

```
(base) devengqc@17-CN0065CL-1:~/git/projects/fastai_nbs$ nbdev_preview
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/parallel.py", line 46, in _call
    return g(item)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve_drv.py", line 22, in main
    if src.suffix=='.ipynb': exec_nb(src, dst, x)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve_drv.py", line 16, in exec_nb
    cb()(nb)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/processors.py", line 231, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/processors.py", line 210, in end
    widgets = {**old, **new, 'state': {**old['state'], **new['state']}}
KeyError: 'state'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/devengqc/mambaforge/bin/nbdev_preview", line 8, in <module>
    sys.exit(nbdev_preview())
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/quarto.py", line 270, in nbdev_preview
    cache,cfg,path = _pre_docs(path, n_workers=n_workers, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/quarto.py", line 174, in _pre_docs
    cache = proc_nbs(path, n_workers=n_workers, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve.py", line 76, in proc_nbs
    parallel(nbdev.serve_drv.main, files, n_workers=n_workers, pause=0.01, **kw)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/parallel.py", line 117, in parallel
    return L(r)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/foundation.py", line 98, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/foundation.py", line 106, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/basics.py", line 66, in listify
    elif is_iter(o): res = list(o)
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
KeyError: 'state'

```

Does the `skip_exec` flag not work in markdown cells?

**Comment by hamelsmu** [comment]
Can you make sure you are using the latest version of nbdev from github and the latest pre-release of quarto?

- `pip install -U git+https://github.com/fastai/nbdev.git`
- https://quarto.org/docs/download/prerelease.html

**Comment by deven-gqc** [comment]
@hamelsmu I did both those things, however I get the same error.

**Comment by hamelsmu** [comment]
I was not able to reproduce this error.  Can you create a minimal reproduction of this issue we can test?

**Comment by deven-gqc** [comment]
@hamelsmu Idk how I got it work, its working now.

**Comment by hamelsmu** [comment]
Ok if you find it again please try to minimally recreate it if you don't mind!
