### ISSUE TITLE
AttributeError: path_ when running `nbdev_docs` (2.3.7) in my project

### ISSUE THREAD

**Issue by benoit-cty** [fastai/nbdev#1158]
When running `nbdev_docs` (2.3.7), in my project ends with this traceback:
```
---

  warn(f'Found cells containing imports and other code. See FAQ.\n---\n{cell.source}\n---\n')
/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/processors.py:182: UserWarning: Found cells containing imports and other code. See FAQ.
---
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
---

  warn(f'Found cells containing imports and other code. See FAQ.\n---\n{cell.source}\n---\n')
Traceback (most recent call last):
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/cli.py", line 46, in nbdev_filter
    with redirect_stdout(dn): filt(nb)
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/processors.py", line 231, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/nbdev/frontmatter.py", line 66, in end
    self.fm.update({'output-file': _nbpath2html(Path(self.nb.path_)).name})
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/fastcore/basics.py", line 247, in __getattr__
    def __getattr__(self,k): return self[k] if k in self else stop(AttributeError(k))
  File "/home/jupyter-benoit/leximpact-prepare-data/.venv/lib/python3.8/site-packages/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: path_
```
How could I debug this ?
At least know the name of the notebook ?

I have many "Found cells containing imports and other code." warning above without traceback.

With previous version "2.2.10" it was working.

**Comment by dleen** [comment]
FYI: The "Found cells containing..." warning will give more information after #938 

Are you able to share the repo that is causing this issue?

**Comment by benoit-cty** [comment]
Thanks, the repo on the branch having the problem: https://git.leximpact.dev/leximpact/leximpact-prepare-data/-/tree/mahdi/
I've fixed the nbdev version to "2.2.10" and it works fine, so no worry, I could wait for a future release  with https://github.com/fastai/nbdev/issues/938

**Comment by seeM** [comment]
nbdev v2.3 should work if you remove the `ipynb-filters: [nbdev_filter]` line from your `_quarto.yml`. The context is that we no longer use quarto to run these "notebook filters" and instead run them ourselves, leading to much faster performance :) See this forum post for more: https://forums.fast.ai/t/upcoming-changes-in-v2-3-edit-now-released/98905

**Comment by benoit-cty** [comment]
Thanks, it solved my issue.
I've also added nbdev.yml in metadata-files:
```
metadata-files: 
  - sidebar.yml
  - nbdev.yml
  - custom.yml
```
But I have a new problem:
```
[ 2/51] survey_scenario/modules/inflation_and_calibration_margins.ipynb
ERROR: SyntaxError: Unexpected token x in JSON at position 6
```
It is a small notebook that looks good : https://git.leximpact.dev/leximpact/leximpact-prepare-data/-/blob/master/notebooks/extractions_dads_postes/40_categorical_bi-variate.ipynb

Is there something else to do to migrate from 2.2 to 2.3 ?

Thanks for your great work !

**Comment by seeM** [comment]
Could you take a look at the corresponding notebook in the `_proc` folder? That should show what it looks like after nbdev processes it and before quarto tries to render it. I suspect something went wrong there.

**Comment by thisiswhereitype** [comment]
I am having this issue surface in 2.3.12 - whether running `nbdev_readme` or `nbdev_docs`
