### ISSUE TITLE
pre-commit hook causing InterpolationMissingOptionError in python3.9/configparser.py

### ISSUE THREAD

**Issue by AndreasThinks** [fastai/nbdev#1159]
I'm trying to run the pre-commit hook, and it's failing no matter which Python version I try and use

See traceback below (edited to hide local folder details)
```
Traceback (most recent call last):
  File "/homen/bin/nbdev_export", line 8, in <module>
    sys.exit(nbdev_export())
  File "/home/n/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/me_reporting_inflation/lib/python3.9/site-packages/nbdev/doclinks.py", line 135, in nbdev_export
    _build_modidx()
  File "/home/an/lib/python3.9/site-packages/nbdev/doclinks.py", line 93, in _build_modidx
    res['settings'] = {k:v for k,v in get_config().d.items()
  File "/home/aon/lib/python3.9/site-packages/nbdev/doclinks.py", line 93, in <dictcomp>
    res['settings'] = {k:v for k,v in get_config().d.items()
  File "/usr/lib/python3.9/_collections_abc.py", line 850, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib/python3.9/configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.9/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.9/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.9/configparser.py", line 434, in _interpolate_some
    raise InterpolationMissingOptionError(
configparser.InterpolationMissingOptionError: Bad value substitution: option 'lib_name' in section 'DEFAULT' contains an interpolation key 'repo' which is not a valid option name. Raw value: '%(repo)s'
```

**Comment by dleen** [comment]
Can you share your `settings.ini`? (or link to the repo if it exists)

**Comment by seeM** [comment]
Your `settings.ini` is missing the `repo` key (which might have been made a required key in a newer version of nbdev)

**Comment by AndreasThinks** [comment]
Strange, I'd literally just pip installed nbdev... will go have a look,

**Comment by ruddyscent** [comment]
Did you solve the problem? I'm having the same issue.
