### ISSUE TITLE
Key error if widgets is missing `state`

### ISSUE THREAD

**Issue by deven-gqc** [fastai/nbdev#1167]
This issue is from #1127 .

@hamelsmu I think I am now able to reproduce the error. Here is a minimal repo for that. https://github.com/deven-gqc/test-key-state-error.

The weird thing is it passes the CI in GitHub Actions, but I keep getting the error locally. 

```bash
(base) devengqc@17-CN0065CL-1:~/git/public/test-key-state-error$ nbdev_preview
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/parallel.py", line 46, in _call
    return g(item)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve_drv.py", line 22, in main
    if src.suffix=='.ipynb': exec_nb(src, dst, x)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve_drv.py", line 16, in exec_nb
    cb()(nb)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/processors.py", line 231, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/processors.py", line 210, in end
    widgets = {**old, **new, 'state': {**old['state'], **new['state']}}
KeyError: 'state'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/devengqc/mambaforge/bin/nbdev_preview", line 8, in <module>
    sys.exit(nbdev_preview())
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/quarto.py", line 270, in nbdev_preview
    cache,cfg,path = _pre_docs(path, n_workers=n_workers, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/quarto.py", line 174, in _pre_docs
    cache = proc_nbs(path, n_workers=n_workers, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/serve.py", line 76, in proc_nbs
    parallel(nbdev.serve_drv.main, files, n_workers=n_workers, pause=0.01, **kw)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/parallel.py", line 117, in parallel
    return L(r)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/foundation.py", line 98, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/foundation.py", line 106, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/basics.py", line 66, in listify
    elif is_iter(o): res = list(o)
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/devengqc/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
KeyError: 'state'
```

**Comment by seeM** [comment]
Could it be that you’re on an older version of some dependency locally vs in GitHub Actions? Perhaps execnb?

**Comment by deven-gqc** [comment]
@seeM 
I am running the latest versions locally
fastcore: 1.5.27
execnb: 0.1.4
nbdev: 2.3.8

**Comment by hamelsmu** [comment]
You are one version behind, you should install the latest version from GitHub

**Comment by deven-gqc** [comment]
@hamelsmu The issue still persists after downloading the latest version from GitHub.

**Comment by deven-gqc** [comment]
@seeM @hamelsmu I have figured out the issue. The issue came into picture because of the `widgets` key inside the note. I'm not sure if there is a mechanism currently to handle that key. Getting rid of the `widgets` key inside the notebook fixes the issue.

**Comment by udaylunawat** [comment]
@deven-gqc @seeM @hamelsmu 

> @seeM @hamelsmu I have figured out the issue. The issue came into picture because of the `widgets` key inside the note. I'm not sure if there is a mechanism currently to handle that key. Getting rid of the `widgets` key inside the notebook fixes the issue.

How do you get rid of the widget key?

I figured out that creating a new empty notebook, and copying the cells from the existing notebook solved this issue.

The weird thing was that even if you delete all cells in the existing notebook, it'll still raise this issue.
So, it's not because of the cells but because of the widget state which exists in the notebook regardless of the cells.

**Comment by deven-gqc** [comment]
> I figured out that creating a new empty notebook, and copying the cells from the existing notebook solved this issue.

@udaylunawat I did that as well.

> How do you get rid of the widget key?

I had opened the notebook with a text editor and deleted that key.
