### ISSUE TITLE
error with `nbdev_export`

### ISSUE THREAD

**Issue by deven-gqc** [fastai/nbdev#1188]
I reorganized notebooks in my repo and doing a `nbdev_export` just crashes. From the error visible right row, it is not possible to figure out which notebook is causing this error.

```bash
(base) devengqc@17-CN0065CL-1:~/git/projects/notebooks$ nbdev_export
Traceback (most recent call last):
  File "/home/devengqc/mambaforge/bin/nbdev_export", line 8, in <module>
    sys.exit(nbdev_export())
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/doclinks.py", line 136, in nbdev_export
    _build_modidx()
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/doclinks.py", line 98, in _build_modidx
    res['syms'].update(_get_modidx((dest.parent/file).resolve(), code_root, nbs_path=nbs_path))
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/doclinks.py", line 69, in _get_modidx
    for cell in _iter_py_cells(py_path):
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/nbdev/doclinks.py", line 52, in _iter_py_cells
    nb,idx = top.split()
ValueError: too many values to unpack (expected 2)
```

**Comment by hamelsmu** [comment]
Can you please provide us with a minimally reproducible example of this error?

**Comment by seeM** [comment]
I suspect this is the same issue as #1153. @deven-gqc could you please check if your Python file has comments like `# %%` or ` # %% [markdown]` or anything except the format created by nbdev which only has two items e.g. `# %% ../nbs/api/doclinks.ipynb 9`

**Comment by deven-gqc** [comment]
@seeM  The py file does not have any of those comments. Also, a thing to note in that case is that running ’nbdev_export’ deletes the `_modidx.py`

**Comment by seeM** [comment]
Got it. I've just made a PR (#1211) to print more a helpful error message. Will close this when it's merged.
