### ISSUE TITLE
Error using nbdev_export in Colab

### ISSUE THREAD

**Issue by Jaume-JCI** [fastai/nbdev#1189]
I am getting this error when I run !nbdev_export in Colab. It used to run correctly until yesterday:

```python
Traceback (most recent call last):
  File "/usr/local/bin/nbdev_export", line 8, in <module>
    sys.exit(nbdev_export())
  File "/usr/local/lib/python3.7/dist-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/usr/local/lib/python3.7/dist-packages/nbdev/doclinks.py", line 135, in nbdev_export
    _build_modidx()
  File "/usr/local/lib/python3.7/dist-packages/nbdev/doclinks.py", line 93, in _build_modidx
    res['settings'] = {k:v for k,v in get_config().d.items()
  File "/usr/local/lib/python3.7/dist-packages/nbdev/doclinks.py", line 93, in <dictcomp>
    res['settings'] = {k:v for k,v in get_config().d.items()
  File "/usr/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib/python3.7/configparser.py", line 1252, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.7/configparser.py", line 799, in get
    d)
  File "/usr/lib/python3.7/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.7/configparser.py", line 434, in _interpolate_some
    option, section, rawval, var) from None
configparser.InterpolationMissingOptionError: Bad value substitution: option 'lib_name' in section 'DEFAULT' contains an interpolation key 'repo' which is not a valid option name. Raw value: '%(repo)s'
```

**Comment by hamelsmu** [comment]
nbdev is not tested to work in Google Colab.  Either way, it is hard to help in this situation b/c you have not provided a minimally reproducible example.

**Comment by Jaume-JCI** [comment]
Thank you again! I can provide such example if Colab is going to be supported, please let me know.

**Comment by seeM** [comment]
@Jaume-JCI This specific error message is saying that your `settings.ini` file is missing the `repo` key. That should be set to the name of your repo

**Comment by Jaume-JCI** [comment]
@seeM Thank you very much. I just saw where the problem happened: in the colab notebook, I had run "!cd <my_repo>" in order to change the working dir in the notebook... I should have run "cd <my_repo>" instead... I realized this while trying to show you that settings.ini does have the `repo` key... my mistake, sorry about that!
