### ISSUE TITLE
nbdev_docs fails 

### ISSUE THREAD

**Issue by Jaume-JCI** [fastai/nbdev#1200]
when running `nbdev_docs` on the `nbdev` repo, it doesn't completely fail (although we need to install the svg.py library by doing `pip install -e .[dev]`, and quarto ends up complaining with some error messages).

However, when running `nbdev_docs` on my repo, it fails as follows:

```python
Traceback (most recent call last):
  File "/anaconda/envs/dsblocksn2/bin/nbdev_filter", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_filter')())
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/fastcore/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/nbdev/nbdev/cli.py", line 46, in nbdev_filter
    with redirect_stdout(dn): filt(nb)
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/nbdev/nbdev/processors.py", line 243, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/nbdev/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/nbdev/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/nbdev/nbdev/frontmatter.py", line 66, in end
    self.fm.update({'output-file': _nbpath2html(Path(self.nb.path_)).name})
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/fastcore/fastcore/basics.py", line 247, in __getattr__
    def __getattr__(self,k): return self[k] if k in self else stop(AttributeError(k))
  File "/home/jcidatascience/jaume/workspace/other/nbdevv2/fastcore/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: path_
```
I digged a bit and found the error happens on this command:
```python
quarto render "<my_repo>/_proc/index.ipynb" -o README.md -t gfm --no-execute"
```
If I run this command separately from command line, it doesn't work either. I tried to set breakpoints in `nbdev_filter ()` to dig more, but didn't succeed unfortunately.

**Comment by hamelsmu** [comment]
1. Are you using the latest versions of quarto and nbdev?  Install nbdev `pip install git+https://github.com/fastai/nbdev.git` from git and also use the latest [pre-release of quarto](https://quarto.org/docs/download/prerelease.html)
2. You have not provided a way for us to reproduce your error, so it will be impossible to help you.  Can you provide a reproducible example?

**Comment by Jaume-JCI** [comment]
Thank you for your response! I just pulled the latest commit from nbdev and installed in dev mode (pip install -e ). I also installed the pre-release you indicated (do  you know if there is a way to check that my conda env is using this pre-release and not the one installed by nbdev originally?). I still get the same error. 

In order to reproduce, I followed these steps from scratch:
```bash
yes | conda create -n reproduce pip
conda activate reproduce
pip install git+https://github.com/fastai/nbdev.git
wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.262/quarto-1.2.262-linux-amd64.deb
sudo apt install ./quarto-1.2.262-linux-amd64.deb
git clone https://github.com/Jaume-JCI/ds-blocks.git -b reproduce
cd ds-blocks
pip install -e .[dev]
nbdev_docs
```

Please let me know if this is good enough. Thanks!

**Comment by tylere** [comment]
I am running into the same issue when I set `recursive = True` in `settings.ini`

This is consistent with @Jaume-JCI's sample repo, which has [recursive = 1](https://github.com/Jaume-JCI/ds-blocks/blob/main/settings.ini#L11)

**Comment by Jaume-JCI** [comment]
Thanks @seeM. I double-checked, but there are no `ipynb-filters` in any of the '_quarto.yml' files. You may check that if you want in the repo I have indicated when describing how to reproduce this issue above.
