### ISSUE TITLE
Unable to use nbdev_preview on my Apple M1 Pro macOS Monterey.

### ISSUE THREAD

**Issue by thigm85** [fastai/nbdev#1203]
I am unable to use `nbdev_preview` on my Apple M1 Pro macOS Monterey. I think this is related to https://github.com/fastai/nbdev/issues/1040 but not quite the same @hamelsmu 

I get 
```
Quarto is not installed. We will download and install it for you.
```
every time I try `nbdev_preview`. I get the message that Quarto is sucessfully installed but the command fails with

```
Traceback (most recent call last):
  File "/Users/thiagomartins/.local/share/virtualenvs/turbo-p2f-PXXH/bin/nbdev_preview", line 8, in <module>
    sys.exit(nbdev_preview())
  File "/Users/thiagomartins/.local/share/virtualenvs/turbo-p2f-PXXH/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/thiagomartins/.local/share/virtualenvs/turbo-p2f-PXXH/lib/python3.10/site-packages/nbdev/quarto.py", line 283, in nbdev_preview
    with fs_watchdog(_f, path): subprocess.run(['quarto','preview']+xtra)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'quarto'
```

**Comment by thigm85** [comment]
This solved my issue: https://github.com/quarto-dev/quarto-cli/issues/1819 

Specifically `export PATH=$PATH:/Applications/quarto/bin/`
