### ISSUE TITLE
nbdev_readme broken on python 3.7

### ISSUE THREAD

**Issue by xl0** [fastai/nbdev#1255]
shutil.copytree(... dirs_exist_ok=True) was intriduced only in Python 3.8:

https://docs.python.org/3/library/shutil.html#shutil.copytree

```
$ nbdev_readme
pandoc -o README.md
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  output-file: index.html
  standalone: true
  default-image-extension: png
  
metadata
  description: 'After all, you are only human.'
  title: "\U0001F498 Lovely JAX"
  
Output created: _docs/README.md

Traceback (most recent call last):
  File "/home/xl0/mambaforge/envs/py37/bin/nbdev_readme", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_readme')())
  File "/home/xl0/mambaforge/envs/py37/lib/python3.7/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/ssd/xl0/work/code/nbdev/nbdev/quarto.py", line 216, in nbdev_readme
    if _rdmi.exists(): copytree(_rdmi, cfg_path/_rdmi.name, dirs_exist_ok=True) # Move Supporting files for README
  File "/home/xl0/mambaforge/envs/py37/lib/python3.7/site-packages/fastcore/shutil.py", line 8, in _f
    def _f(src, dst, *args, **kwargs): return f(str(src), str(dst), *args, **kwargs)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
```

**Comment by xl0** [comment]
Actually, might be best to address this report to `fastcore`.

**Comment by xl0** [comment]
My bad, the report belongs here. :)

**Comment by hamelsmu** [comment]
@jph00 Python will EOL 3.7 [in 5 months ](https://endoflife.date/python) should we just state that we support 3.8+
