### ISSUE TITLE
Git clone a repo and running nbdev_new produces a parsing error in the JSON file

### ISSUE THREAD

**Issue by lifeofborna** [fastai/nbdev#1278]
Hey, im nbdev and I'm trying to initialize and use nbdev on our repo. But when trying to initialize it produces a JSON error. 

git cloned this repo with SSH https://github.com/Origami-TinyML/tflm_hello_world
> pip install nbdev, the latest version
> nbdev_new
>json parsing error?
>all the other commands such as >nbdev_docs will also crash.

But if I download the repo as a zip file and run nbdev it works perfectly fine. Is there something I'm missing out? Thanks in advance!

<details>
  <summary>When running nbdev_new</summary>

  ``error message:

workingdir$  nbdev_new
/home/b/.local/lib/python3.10/site-packages/ghapi/core.py:101: UserWarning: Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated
  else: warn('Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated')
repo = tflm_hello_world # Automatically inferred from git
branch = main # Automatically inferred from git
user = Origami-TinyML # Automatically inferred from git
author = Your Name # Automatically inferred from git
author_email = you@example.com # Automatically inferred from git
description = Run "Hello World" of TensorFlow Lite for micro automatically in Docker # Automatically inferred from git
settings.ini created.
Traceback (most recent call last):
  File "/home/b/.local/bin/nbdev_new", line 8, in <module>
    sys.exit(nbdev_new())
  File "/home/b/.local/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/b/.local/lib/python3.10/site-packages/nbdev/cli.py", line 108, in nbdev_new
    nbdev_export.__wrapped__()
  File "/home/b/.local/lib/python3.10/site-packages/nbdev/doclinks.py", line 137, in nbdev_export
    for f in files: nb_export(f)
  File "/home/b/.local/lib/python3.10/site-packages/nbdev/export.py", line 48, in nb_export
    nb = NBProcessor(nbname, [exp]+L(procs), debug=debug)
  File "/home/b/.local/lib/python3.10/site-packages/nbdev/process.py", line 92, in __init__
    self.nb = read_nb(path) if nb is None else nb
  File "/home/b/.local/lib/python3.10/site-packages/execnb/nbio.py", line 57, in read_nb
    res = dict2nb(_read_json(path, encoding='utf-8'))
  File "/home/b/.local/lib/python3.10/site-packages/execnb/nbio.py", line 16, in _read_json
    return loads(Path(self).read_text(encoding=encoding, errors=errors))
  File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 19 column 13 (char 307)

  
  ```
</details>

**Comment by GabrielFernandezFernandez** [comment]
Hi,
I had the same problem and fixed it by removing the quotation mark from the repo description, deleting the local files in the repo's root folder, and running nbdev_new again. The error occurs when running nbdev_new and also during workflow actions that fail.
