### ISSUE TITLE
Feature request? How to update workflows?

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1279]
`fastai/workflows/nbdev-ci@master` fails as

> INFO: pip is looking at multiple versions of spot-mark-gene[dev] to determine which version is compatible with other requirements. This could take a while.
[273](https://github.com/<user-name>/<project-name>/actions/runs/4055184782/jobs/6977973063#step:2:285)
ERROR: Package '<project-name>' requires a different Python: 3.9.16 not in '>=3.10'

So I went to try and find / figure out what to do about this and I can't find it under actions. So where do I go to find the base workflows so I can update them?

**Comment by deven367** [comment]
hey @dsm-72, the workflows come from the https://github.com/fastai/workflows repo. They are based on the idea of resusable workflows. You can read more about it over &rarr; **[here](https://docs.github.com/en/actions/using-workflows/reusing-workflows)**

If you wish to use python3.10, you can do that in the following fashion.
```yml
name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    with:
      python: 3.10
    steps: [uses: fastai/workflows/nbdev-ci@master]

```

**Comment by dsm-72** [comment]
@deven367 


```
[Invalid workflow file: .github/workflows/test.yaml#L7](https://github.com/<user>/<project>/actions/runs/4075076640/workflow)
The workflow is not valid. .github/workflows/test.yaml (Line: 7, Col: 5): Unexpected value 'with'
```

**Comment by deven367** [comment]
@dsm-72 
I tried it myself, it works for me
https://github.com/deven367/test-nbdev/blob/main/.github/workflows/test.yaml

**Comment by deven367** [comment]
@dsm-72 Apologies. There was a syntax error.
```yml
name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          python-version: '3.10'
```

**Comment by dsm-72** [comment]
@deven367 Thanks! Now it is running on push :) and.... now `nbdev_preview` is broken. Reverting these files fixes it.
That doesn't make sense to me since they should be unrelated....
```
(PROJECT) ➜  PROJECT git:(branch) ✗ nbdev_preview 
Traceback (most recent call last):
  File "/Users/USER/miniconda3/envs/PROJECT/bin/nbdev_preview", line 8, in <module>
    sys.exit(nbdev_preview())
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/nbdev/quarto.py", line 270, in nbdev_preview
    cache,cfg,path = _pre_docs(path, n_workers=n_workers, **kwargs)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/nbdev/quarto.py", line 174, in _pre_docs
    cache = proc_nbs(path, n_workers=n_workers, **kwargs)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/nbdev/serve.py", line 76, in proc_nbs
    parallel(nbdev.serve_drv.main, files, n_workers=n_workers, pause=0.01, **kw)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/fastcore/parallel.py", line 117, in parallel
    return L(r)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/fastcore/foundation.py", line 98, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/fastcore/foundation.py", line 106, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/site-packages/fastcore/basics.py", line 66, in listify
    elif is_iter(o): res = list(o)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/USER/miniforge3/envs/PROJECT/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by deven367** [comment]
`nbdev_preview` uses parallel processing by default which makes the stack trace useless
Can you run it with `nbdev_preview --n_workers 0`?

**Comment by dsm-72** [comment]
Also any idea on why this might happen?
Ran this again just to make sure...
```
$ nbdev_install_hooks 
Hooks are installed.
```


```
Check that strip out was unnecessary
[783](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:795)
+ git status -s
[784](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:796)
 M nbs/##_my_file.ipynb
[785](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:797)
++ git status --porcelain -uno
[786](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:798)
+ [[ -n  M nbs/##_my_file.ipynb ]]
[787](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:799)
+ git status -uno
[788](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:800)
On branch TEST_BRANCH
[789](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:801)
Your branch is up to date with 'origin/TEST_BRANCH'.
[790](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:802)

[791](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:803)
Changes not staged for commit:
[792](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:804)
  (use "git add <file>..." to update what will be committed)
[793](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:805)
  (use "git restore <file>..." to discard changes in working directory)
[794](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:806)
	modified:   nbs/##_my_file.ipynb
[795](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:807)

[796](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:808)
no changes added to commit (use "git add" and/or "git commit -a")
[797](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:809)
+ echo -e '!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks'
[798](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:810)
+ false
[799](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:811)
!!! Detected unstripped out notebooks
[800](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:812)
!!!Remember to run nbdev_install_hooks
[801](https://github.com/USER/PROJECT/actions/runs/4075784512/jobs/7022648909#step:2:813)
Error: Process completed with exit code 1.
```

**Comment by deven367** [comment]
once the hooks are installed, run `nbdev_prepare` and try to find the error. Once you find the problematic cell, commit everything nbs and the py files, it should probably fix the error.

**Comment by dsm-72** [comment]
Thank you so much for the assistance!

**Comment by dsm-72** [comment]
@deven367 
```
> Warning: Unexpected input(s) 'python-version', valid inputs are ['pre', 'version', 'skip_test', 'flags']
Run fastai/workflows/nbdev-ci@master
  with:
    python-version: 3.10
    version: 3.9
```

**Comment by deven367** [comment]
@dsm-72 this should fix it, `python-version` is not a valid input to the workflow
```yml
name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: '3.10'
```
