### ISSUE TITLE
Confusing error if ipynb-filters are used

### ISSUE THREAD

**Issue by rleyvasal** [fastai/nbdev#1298]
## Followed tutorial but getting error

Followed the [nbdev tutorial](https://nbdev.fast.ai/tutorials/tutorial.html) for nbdev_cards example and did `git push` results.  but I keep getting errors about CI and Github pages failing because quarto needs root access.

Also  ran `nbdev_clean` but the problem persists

![installing quarto requires root](https://user-images.githubusercontent.com/61335136/219520895-995855e6-51ea-40d9-b925-5fc8fe02de6a.png)

## Minimal reproducible example

https://github.com/rleyvasal/nbdev_cards

**Comment by tourdownunder** [comment]
The error is a not an permission error about root access.

It is `AttributeError: path_`. From your most recent action I have downloaded the following log:

```sh
Quarto is not installed. We will download and install it for you.
Installing or upgrading quarto -- this requires root access.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbdev/cli.py", line 46, in nbdev_filter
    with redirect_stdout(dn): filt(nb)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbdev/processors.py", line 243, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbdev/frontmatter.py", line 66, in end
    self.fm.update({'output-file': _nbpath2html(Path(self.nb.path_)).name})
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fastcore/basics.py", line 247, in __getattr__
    def __getattr__(self,k): return self[k] if k in self else stop(AttributeError(k))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: path_
Error: Process completed with exit code 1.
```

I had a look at https://github.com/fastai/workflows and didn't see any recent commits that may have broke things. So I followed the tutorial with https://github.com/tourdownunder/nbdev-hello-world and don't get this issue. 

It may have been intermittent. What happens if you run it again?

**Comment by tourdownunder** [comment]
What versions of `fastcore` and `nbdev` do you have?

```sh
fastcore==1.5.28
nbdev==2.3.12
```

If they are different it might be worth updating.

**Comment by jvivian** [comment]
> What versions of `fastcore` and `nbdev` do you have?
> 
> ```shell
> fastcore==1.5.28
> nbdev==2.3.12
> ```
> 
> If they are different it might be worth updating.

I am getting the same error and have the same versions installed. It looks like `nbdev_filter` is actually what is failing

```
nbdev_prepare
Success.
Traceback (most recent call last):
  File "<>/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "<>/lib/python3.8/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "<>/lib/python3.8/site-packages/nbdev/cli.py", line 46, in nbdev_filter
    with redirect_stdout(dn): filt(nb)
  File "<>/lib/python3.8/site-packages/nbdev/processors.py", line 243, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "<>/lib/python3.8/site-packages/nbdev/process.py", line 126, in process
    for proc in self.procs: self._proc(proc)
  File "<>/lib/python3.8/site-packages/nbdev/process.py", line 120, in _proc
    if hasattr(proc,'end'): proc.end()
  File "<>/lib/python3.8/site-packages/nbdev/frontmatter.py", line 66, in end
    self.fm.update({'output-file': _nbpath2html(Path(self.nb.path_)).name})
  File "<>/lib/python3.8/site-packages/fastcore/basics.py", line 247, in __getattr__
    def __getattr__(self,k): return self[k] if k in self else stop(AttributeError(k))
  File "<>/lib/python3.8/site-packages/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: path_
```

Will update if I figure it out

**Comment by ababino** [comment]
This happened to me after upgrading `nbdev`. I deleted (move it to another folder) the `_quarto.yml` file and run `nbdev_prepare` and now it works. I hope this is useful.

**Comment by jvivian** [comment]
> This happened to me after upgrading `nbdev`. I deleted (move it to another folder) the `_quarto.yml` file and run `nbdev_prepare` and now it works. I hope this is useful.

Not sure how I ran into it while setting up from scratch but that definitely solved the issue. Much appreciated @ababino !

**Comment by rleyvasal** [comment]
I  am still getting github emails about `Run failed: CI ..`   and `Run failed: Deploy to github`. 

I have updated to the latest versions of `fastcore` and `nbdev` and ran `nbdev_prepare`  before commiting my changes.

```
fastcore==1.5.28
nbdev==2.3.12
```

**Comment by nicole-brewer** [comment]
I'm also getting this error while setting up from scratch

**Comment by seeM** [comment]
I think this should be fixed by using the latest version of nbdev locally, and ensuring `ipynb-filter` doesn't appear in your `_quarto.yml`. I'm not sure what's causing it to appear there in the first place -- I can only suspect an older version of nbdev

**Comment by seeM** [comment]
We're introducing a more useful error message in https://github.com/fastai/nbdev/pull/1332. Also see [this forum post](https://forums.fast.ai/t/failed-github-ci-when-following-end-to-end-walkthrough/104442/16?u=seem) for fixes to related issues.
