### ISSUE TITLE
`nbdev_release_gh` fails with no feedback

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#1302]
Calling `nbdev_release_gh` I just get this, and I don't know where even to start to debug or create a minimal example:

```bash
❯ nbdev_release_gh
Traceback (most recent call last):
  File "/Users/klay6683/miniforge3/envs/py310/bin/nbdev_release_gh", line 10, in <module>
    sys.exit(release_gh())
  File "/Users/klay6683/miniforge3/envs/py310/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/klay6683/miniforge3/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 127, in release_gh
    Release().changelog()
  File "/Users/klay6683/miniforge3/envs/py310/lib/python3.10/site-packages/nbdev/release.py", line 57, in __init__
    if not token: raise Exception('Failed to find token')
Exception: Failed to find token
```

My repo is here:  https://github.com/michaelaye/nbplanetary

nbdev version: 2.3.12
OS: macOS 12.6.1

**Comment by michaelaye** [comment]
ok this is weird, this is related to the Github token, which I clearly did create a while ago, as evident by the .gitignore that already includes the `token` ignore, but my token file isn't there. Very weird.
