### ISSUE TITLE
Fails to make_readme() from notebook that consists of single markdown cell

### ISSUE THREAD

**Issue by antonbabkin** [fastai/nbdev#175]
I have index.ipynb notebook that only has one markdown cell in it, and when I try do `nbdev_build_docs`, I get an error below. If a second cell (markdown or code) is added, `README.md` is created successfully. 

```
Traceback (most recent call last):
  File "/home/babkin/miniconda3/envs/nbdev/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/home/babkin/miniconda3/envs/nbdev/lib/python3.7/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/home/babkin/miniconda3/envs/nbdev/lib/python3.7/site-packages/nbdev/cli.py", line 103, in nbdev_build_docs
    if mk_readme: make_readme()
  File "/home/babkin/miniconda3/envs/nbdev/lib/python3.7/site-packages/nbdev/cli.py", line 86, in make_readme
    convert_md(index_fn, Config().config_file.parent, jekyll=False)
  File "/home/babkin/miniconda3/envs/nbdev/lib/python3.7/site-packages/nbdev/export2html.py", line 545, in convert_md
    for n,o in export[1]['outputs'].items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by sgugger** [comment]
Fixed by #177
