### ISSUE TITLE
Some tbs I got running nbdev_conda_package

### ISSUE THREAD

**Issue by tyoc213** [fastai/nbdev#201]
* If I run outside of a nbdev repo I got

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/fastai2/bin/nbdev_conda_package", line 10, in <module>
    sys.exit(nbdev_conda_package())
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/cli.py", line 299, in nbdev_conda_package
    write_conda_meta(path)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 51, in write_conda_meta
    name,d1,d2 = _get_conda_meta()
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 15, in _get_conda_meta
    cfg = Config()
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/imports.py", line 42, in __init__
    assert self.config_file.exists(), "Use `create_config` to create settings.ini for the first time"
AssertionError: Use `create_config` to create settings.ini for the first time

```

* If I run in a previous nbdev repo I got

```
nbdev_conda_package 
Traceback (most recent call last):
  File "/home/miniconda3/envs/fastai2/bin/nbdev_conda_package", line 10, in <module>
    sys.exit(nbdev_conda_package())
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/cli.py", line 299, in nbdev_conda_package
    write_conda_meta(path)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 51, in write_conda_meta
    name,d1,d2 = _get_conda_meta()
  File "/home/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 25, in _get_conda_meta
    pypi_t = urllib.request.urlopen(f'https://pypi.org/pypi/{name}/{ver}/json').read()
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

* ANd on a newly created nbdev_new I got

```
$ nbdev_conda_package 
Traceback (most recent call last):
  File "/home/tyoc213/miniconda3/envs/fastai2/bin/nbdev_conda_package", line 10, in <module>
    sys.exit(nbdev_conda_package())
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/cli.py", line 299, in nbdev_conda_package
    write_conda_meta(path)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 51, in write_conda_meta
    name,d1,d2 = _get_conda_meta()
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/conda.py", line 25, in _get_conda_meta
    pypi_t = urllib.request.urlopen(f'https://pypi.org/pypi/{name}/{ver}/json').read()
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/tyoc213/miniconda3/envs/fastai2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

Probably all is because I havent logged or downloaded conda things related to packages?

**Comment by jph00** [comment]
It relies on a pip module already being available on pypi. We should document that! :)
