### ISSUE TITLE
Feature request: linked code-cell outputs

### ISSUE THREAD

**Issue by koenvanderveen** [fastai/nbdev#240]
Hey, it would be really cool if it would be possible to create links docs in cell outputs as well. I changed a line in my local installation that allows for this, but ran into some problem with build_lib when trying to make a PR. The line I changed was in treat_backticks():

```
if cell['cell_type'] == 'markdown':
    cell['source'] = add_doc_links(cell['source'])
```

to 
```
if cell['cell_type'] == 'markdown':
    cell['source']  = add_doc_links(cell['source'])
elif cell["cell_type"] == "code":
    cell['outputs']  = add_doc_links(cell['outputs'])
```

**Comment by koenvanderveen** [comment]
Oh, I see this approach has some bugs. I will look into them

**Comment by jph00** [comment]
Feel free to do a PR, but if you do please provide usage examples so I understand the purpose of the feature.

**Comment by koenvanderveen** [comment]
I would like to make one, but when I clone the repo and run the tests I get quite a few errors. Do you want me to ignore them? I want to make sure I am not introducing any errors with my changes, but it is kind off challenging to do so when the tests are not passing initially.

FYI my tests result in:

```
testing /Users/koen/workspace/nbdev/nbs/02_showdoc.ipynb
testing /Users/koen/workspace/nbdev/nbs/00_export.ipynb
testing /Users/koen/workspace/nbdev/nbs/03_export2html.ipynb
testing /Users/koen/workspace/nbdev/nbs/01_sync.ipynb
testing /Users/koen/workspace/nbdev/nbs/04_test.ipynb
testing /Users/koen/workspace/nbdev/nbs/06_cli.ipynb
testing /Users/koen/workspace/nbdev/nbs/05_merge.ipynb
testing /Users/koen/workspace/nbdev/nbs/05a_conda.ipynb
testing /Users/koen/workspace/nbdev/nbs/07_clean.ipynb
testing /Users/koen/workspace/nbdev/nbs/99_search.ipynb
testing /Users/koen/workspace/nbdev/nbs/index.ipynb
testing /Users/koen/workspace/nbdev/nbs/magic_flags.ipynb
Error in /Users/koen/workspace/nbdev/nbs/07_clean.ipynb:
An error occurred while executing the following cell:
------------------
from nbdev import *
%nbdev_default_export clean
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6152506af70f> in <module>
----> 1 from nbdev import *
      2 get_ipython().run_line_magic('nbdev_default_export', 'clean')

~/workspace/nbdev/nbs/nbdev/__init__.py in <module>
      6 if IN_IPYTHON:
      7     from .flags import *
----> 8     from .showdoc import show_doc
      9     from .export import notebook2script

ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)
ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)

testing /Users/koen/workspace/nbdev/nbs/nbdev_callbacks.ipynb
testing /Users/koen/workspace/nbdev/nbs/tutorial.ipynb
Error in /Users/koen/workspace/nbdev/nbs/03_export2html.ipynb:
An error occurred while executing the following cell:
------------------
fake_nb = {k:v for k,v in tst_nb.items() if k != 'cells'}
fake_nb['cells'] = [tst_nb['cells'][0].copy()] + added_cells
fake_nb = execute_nb(fake_nb, mod='export')
assert len(fake_nb['cells'][-1]['outputs']) > 0
------------------

---------------------------------------------------------------------------
CellExecutionError                        Traceback (most recent call last)
<ipython-input-80-0628e998a0d0> in <module>
      1 fake_nb = {k:v for k,v in tst_nb.items() if k != 'cells'}
      2 fake_nb['cells'] = [tst_nb['cells'][0].copy()] + added_cells
----> 3 fake_nb = execute_nb(fake_nb, mod='export')
      4 assert len(fake_nb['cells'][-1]['outputs']) > 0

<ipython-input-75-e46623361237> in execute_nb(nb, mod, metadata, show_doc_only)
     19     metadata = metadata or {}
     20     pnb = nbformat.from_dict(nb)
---> 21     ep.preprocess(pnb, metadata)
     22     return pnb

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py in preprocess(self, nb, resources, km)
     63             self.resources = resources
     64         self.reset_execution_trackers()
---> 65         self.execute()
     66         return nb, resources

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbclient/util.py in wrapped(*args, **kwargs)
     72     """
     73     def wrapped(*args, **kwargs):
---> 74         return just_run(coro(*args, **kwargs))
     75     wrapped.__doc__ = coro.__doc__
     76     return wrapped

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbclient/util.py in just_run(coro)
     51         nest_asyncio.apply()
     52         check_patch_tornado()
---> 53     return loop.run_until_complete(coro)
     54 
     55 

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nest_asyncio.py in run_until_complete(self, future)
     93                 raise RuntimeError(
     94                     'Event loop stopped before Future completed.')
---> 95             return f.result()
     96         finally:
     97             events._set_running_loop(old_running_loop)

/opt/anaconda3/envs/nbdev/lib/python3.7/asyncio/futures.py in result(self)
    179         self.__log_traceback = False
    180         if self._exception is not None:
--> 181             raise self._exception
    182         return self._result
    183 

/opt/anaconda3/envs/nbdev/lib/python3.7/asyncio/tasks.py in __step(***failed resolving arguments***)
    247                 # We use the `send` method directly, because coroutines
    248                 # don't have `__iter__` and `__next__` methods.
--> 249                 result = coro.send(None)
    250             else:
    251                 result = coro.throw(exc)

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbclient/client.py in async_execute(self, reset_kc, **kwargs)
    534                 # when store_history is False
    535                 await self.async_execute_cell(
--> 536                     cell, index, execution_count=self.code_cells_executed + 1
    537                 )
    538             self.set_widgets_metadata()

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbclient/client.py in async_execute_cell(self, cell, cell_index, execution_count, store_history)
    825         if execution_count:
    826             cell['execution_count'] = execution_count
--> 827         self._check_raise_for_error(cell, exec_reply)
    828         self.nb['cells'][cell_index] = cell
    829         return cell

/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/nbclient/client.py in _check_raise_for_error(self, cell, exec_reply)
    733         if self.force_raise_errors or not cell_allows_errors:
    734             if (exec_reply is not None) and exec_reply['content']['status'] == 'error':
--> 735                 raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
    736 
    737     async def async_execute_cell(

CellExecutionError: An error occurred while executing the following cell:
------------------
from nbdev.showdoc import show_doc
from nbdev.export import *
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-df42789a0f4b> in <module>
----> 1 from nbdev.showdoc import show_doc
      2 from nbdev.export import *

~/workspace/nbdev/nbs/nbdev/__init__.py in <module>
      6 if IN_IPYTHON:
      7     from .flags import *
----> 8     from .showdoc import show_doc
      9     from .export import notebook2script

ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)
ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)

CellExecutionError: An error occurred while executing the following cell:
------------------
from nbdev.showdoc import show_doc
from nbdev.export import *
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-df42789a0f4b> in <module>
----> 1 from nbdev.showdoc import show_doc
      2 from nbdev.export import *

~/workspace/nbdev/nbs/nbdev/__init__.py in <module>
      6 if IN_IPYTHON:
      7     from .flags import *
----> 8     from .showdoc import show_doc
      9     from .export import notebook2script

ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)
ImportError: cannot import name 'show_doc' from 'nbdev.showdoc' (/Users/koen/workspace/nbdev/nbs/nbdev/showdoc.py)


Traceback (most recent call last):
  File "/opt/anaconda3/envs/nbdev/bin/nbdev_test_nbs", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_test_nbs')())
  File "/opt/anaconda3/envs/nbdev/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/Users/koen/workspace/nbdev/nbdev/cli.py", line 71, in nbdev_test_nbs
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: The following notebooks failed:
03_export2html.ipynb
```
