### ISSUE TITLE
nbdev_read_nbs -> NameError: name 'IN_NOTEBOOK' is not defined

### ISSUE THREAD

**Issue by ibayer** [fastai/nbdev#266]
Hi,
nbdev is awesome but I'm still running into gotchas from time to time.
This one is especially troublesome as I haven't managed to consistently reproduce it.

I have installed
```
nbdev = "^0.2.18"
fastcore = "^1.0.14"
```

`nbdev_read_nbs` fails with:

```
+ poetry run nbdev_test_nbs
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
  File "/.pyenv/versions/3.7.3/bin/nbdev_test_nbs", line 6, in <module>
    from nbdev.cli import nbdev_test_nbs
  File "/.pyenv/versions/3.7.3/lib/python3.7/site-packages/nbdev/cli.py", line 12, in <module>
    from .export2html import *
  File "/.pyenv/versions/3.7.3/lib/python3.7/site-packages/nbdev/export2html.py", line 15, in <module>
    from .showdoc import *
  File "/.pyenv/versions/3.7.3/lib/python3.7/site-packages/nbdev/showdoc.py", line 14, in <module>
    if IN_NOTEBOOK:
NameError: name 'IN_NOTEBOOK' is not defined
```

using grep I get

```
nbdev$ (master) grep -r IN_NOTEBOOK
nbs/02_showdoc.ipynb:    "if IN_NOTEBOOK:\n",
nbs/02_showdoc.ipynb:       "<h4 id=\"IN_NOTEBOOK\" class=\"doc_header\"><code>IN_NOTEBOOK</code><a href=\"\" class=\"source_link\" style=\"float:right\">[source]</a></h4>\n",
nbs/02_showdoc.ipynb:    "%nbdev_show_doc e DocsTestClass * check_re str IN_NOTEBOOK DocsTestClass . __init__"
nbs/00_export.ipynb:    "    assert IN_NOTEBOOK\n",
docs/export.html:    <span class="k">assert</span> <span class="n">IN_NOTEBOOK</span>
nbdev/showdoc.py:if IN_NOTEBOOK:
tests/00_export.ipynb:    "    assert IN_NOTEBOOK\n",
```

looking deeper:

```
nbdev$ (master) cat nbdev/showdoc.py | head -20
# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_showdoc.ipynb (unless otherwise specified).

__all__ = ['is_enum', 'is_lib_module', 're_digits_first', 'try_external_doc_link', 'is_doc_name', 'doc_link',
           'add_doc_links', 'get_source_link', 'colab_link', 'get_nb_source_link', 'nb_source_link', 'type_repr',
           'format_param', 'show_doc', 'parse_nbdev_show_doc', 'nbdev_show_doc', 'md2html', 'get_doc_link', 'doc']

# Cell
from .imports import *
from .export import *
from .sync import *
from .flags import parse_line
from nbconvert import HTMLExporter

if IN_NOTEBOOK:
    from IPython.display import Markdown,display
    from IPython.core import page

# Cell
def is_enum(cls):
    "Check if `cls` is an enum or another type of class"
```

So it seems that `IN_NOTEBOOK` is indeed defined nowhere. :/ However it worked fine before and stopped working without that I have updated nbdev (I believe).

**Comment by ibayer** [comment]
I just realized that I have been using a fairly early version of nbdev.
After updating to latest version `1.0.18` the problem seems to be gone. :)
