### ISSUE TITLE
Error using nbdev_build_lib in 1.1.0

### ISSUE THREAD

**Issue by KoffeeKatX** [fastai/nbdev#279]
Hi,

I got the error below using version 1.1.0 (on MacOS Catalina, installed via pip, first time using nbdev). I started a new project with "nbdev_new 'project name'", changed the required fields in the settings.ini and then ran 'nbdev_build_lib'. After unsuccessfully trying to remedy the problem myself, I executed the same steps with version 1.0.18, which worked right away.

`Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.8.5/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/Users/xxx/.pyenv/versions/3.8.5/lib/python3.8/site-packages/fastcore/script.py", line 77, in _f
    func(**args.__dict__)
  File "/Users/xxx/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbdev/cli.py", line 21, in nbdev_build_lib
    write_tmpls()
  File "/Users/xxx/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbdev/export2html.py", line 465, in write_tmpls
    path = Path(cfg.get('doc_src_path', cfg.doc_path))
  File "/Users/xxx/.pyenv/versions/3.8.5/lib/python3.8/site-packages/fastcore/foundation.py", line 443, in get
    return self.config_file.parent / v if k.endswith('_path') else v
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'`

Best,
Nico

**Comment by jph00** [comment]
I just tried those steps with 1.1.2 and it worked - could you please try the same, and if it doesn't work, reopen this issue and show me exactly the steps you ran and what happened at each step?
