### ISSUE TITLE
nbdev github CI Action fails with missing path attribute

### ISSUE THREAD

**Issue by bguan** [fastai/nbdev#286]
I have been test driving nbdev on a personal project but I have not been able to figure out why github CI action is failing on the ***Read all notebooks*** step launching ```nbdev_read_nbs``` which passes on my local dev box.

You can see the error on this [run](https://github.com/bguan/mcbbox/runs/1301512611?check_suite_focus=true).

The stack trace:
```
Run nbdev_read_nbs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/nbdev_read_nbs", line 8, in <module>
    sys.exit(nbdev_read_nbs())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/fastcore/script.py", line 77, in _f
    func(**args.__dict__)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/nbdev/test.py", line 130, in nbdev_read_nbs
    files = Config().path("nbs_path").glob('**/*.ipynb') if fname is None else glob.glob(fname)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/fastcore/foundation.py", line 460, in __getattr__
    def __getattr__(self,k):   return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/fastcore/foundation.py", line 252, in stop
    raise e
AttributeError: path
Error: Process completed with exit code 1.
```

This is weird. If my understanding is correct, it is claiming ```Config``` class has no method named ```path```?

**Comment by bguan** [comment]
Adding the ```requirements = nbdev>=1.1.4``` to ***settings.ini*** fixed my issue. I think somehow github CI just pulled in older version of nbdev.
