### ISSUE TITLE
nbdev_build_docs breaks on card example

### ISSUE THREAD

**Issue by koaning** [fastai/nbdev#311]
I'm trying to get `nbdev` to work locally (the jupyter keynote got me curious!) but it seems to hiccup. 

While following the tutorials I get a strange error when I try to generate the docs. This error appears both when I start from scratch when I use [this tutorial](https://nbdev.fast.ai/tutorial.html#Edit-settings.ini) but it also appears when I clone [the repository with the card example](https://github.com/hamelsmu/deck_of_cards). This is what made me think it might be due to a bug instead of my local configuration. 

Running `nbdev_build_lib` and `nbdev_test_nbs` works fine but running `nbdev_build_docs` seems to hiccup. I'm unsure if this issue is related to this repository or maybe to something on the [template repo](https://github.com/fastai/nbdev_template) but I figured it should be mentioned somewhere. I'm running python3.7 on macOS.

Here is the traceback of everything. 

```python
> nbdev_build_lib 
Converted 00_card.ipynb.
Converted 01_deck.ipynb.
Converted index.ipynb.
> nbdev_test_nbs 
testing /Users/vincent/Development/deck_of_cards/00_card.ipynb
testing /Users/vincent/Development/deck_of_cards/01_deck.ipynb
testing /Users/vincent/Development/deck_of_cards/index.ipynb
All tests are passing!
> nbdev_build_docs 
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4custom.ipynb
converting: /Users/vincent/Development/deck_of_cards/index.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4plus.ipynb
'source'
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test3.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4.ipynb
/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/filters/datatypefilter.py:41: UserWarning: Your element with mimetype(s) dict_keys(['application/vnd.raw.v1+json']) is not able to be represented.
  mimetypes=output.keys())
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4jupyter_metadata_timings.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test2.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/many_tracebacks.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4docinfo.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/invalid.ipynb
'source'
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbformat/tests/test4jupyter_metadata.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/UnicodePy3.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/JupyterWidgets.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/SVG.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions-IPY6.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Sleep One.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Disable Stdin.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/update-display-id.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Inline Image.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Interrupt.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Factorials.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions with Cell Tags.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Check History in Memory.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions with Cell Tags-IPY6.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Clear Output.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Parallel Execute A.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Interrupt-IPY6.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Empty Cell.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Parallel Execute B.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Unicode.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/HelloWorld.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/notebook2.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/svg.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/pngmetadata.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/prompt_numbers.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/rawtest.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/attachment.ipynb
[Errno 2] No such file or directory: '/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/attachment:image.png'
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook2.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook3_with_errors.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook4_jpeg.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook1.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/markdown_display_priority.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook_tags.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/Widget_List.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook_jl.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbconvert/tests/files/latex-linked-image.ipynb
converting: /Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/notebook/bundler/tests/resources/empty.ipynb
Conversion failed on the following:
test4plus.ipynb
invalid.ipynb
attachment.ipynb
Traceback (most recent call last):
  File "/Users/vincent/Development/deck_of_cards/venv/bin/nbdev_build_docs", line 10, in <module>
    sys.exit(nbdev_build_docs())
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/fastcore/script.py", line 85, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 660, in nbdev_build_docs
    if fname is None: make_sidebar()
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 725, in make_sidebar
    create_default_sidebar()
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 717, in create_default_sidebar
    dic = {Config().lib_name: _create_default_sidebar()}
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 709, in _create_default_sidebar
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 709, in <listcomp>
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File "/Users/vincent/Development/deck_of_cards/venv/lib/python3.7/site-packages/nbdev/export2html.py", line 699, in _get_title
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vincent/Development/deck_of_cards/docs/attachment.html'
```

**Comment by hamelsmu** [comment]
@koaning the repo with the card of example is [fastai/deck_of_cards](https://github.com/fastai/deck_of_cards) not `hamelsmu/deck_of_cards`

**Comment by hamelsmu** [comment]
I'm not able to reproduce this error.  If you use the right repo as noted above I do not get this error.  (P.S. I checked the docs for links to my fork, but I didn't see any so not sure how you ended up on  my fork).  

```bash
(base) √ github % gh repo clone fastai/deck_of_cards
Cloning into 'deck_of_cards'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (254/254), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 254 (delta 114), reused 215 (delta 76), pack-reused 0
Receiving objects: 100% (254/254), 1.05 MiB | 10.81 MiB/s, done.
Resolving deltas: 100% (114/114), done.
(base) √ github % cd deck_of_cards
(base) √ deck_of_cards % nbdev_build_lib && nbdev_test_nbs && nbdev_build_docs                            (master)deck_of_cards
Converted 00_card.ipynb.
Converted 01_deck.ipynb.
Converted index.ipynb.
testing /Users/hamelsmu/github/deck_of_cards/01_deck.ipynb------------| 0.00% [0/3 00:00<00:00]
testing /Users/hamelsmu/github/deck_of_cards/index.ipynb
testing /Users/hamelsmu/github/deck_of_cards/00_card.ipynb
All tests are passing!
converting: /Users/hamelsmu/github/deck_of_cards/index.ipynb----------| 0.00% [0/1 00:00<00:00]
converting /Users/hamelsmu/github/deck_of_cards/index.ipynb to README.md
(base) √ deck_of_cards %                                                                                  (master)deck_of_cards
```

If you can share a reproducible error from a public repo that I can use to reproduce this error feel free to open a new issue.  Thanks for your help.

**Comment by jph00** [comment]
@koaning perhaps try running `nbdev_build_lib` first?

**Comment by jph00** [comment]
Oh it looks like you have a cell attachment (e.g from pasting an image). Not sure we've got that fully supported automatically, but it's on our todo list.

**Comment by jph00** [comment]
Yup turns out @hamelsmu's fork had an attachment in it (he's removed it now). The fastai repo doesn't have that. So it should work fine with the fastai repo. Feel free to reopen this issue if now.

**Comment by jbulow** [comment]
I ended up with the same error when following the tutorial on https://nbdev.fast.ai/tutorial.html .

I used the template found here https://github.com/fastai/nbdev_template

I'm new to nbdev. Is there any more updated tutorial then the one in the first link? Is there a better template to use to get started?
