### ISSUE TITLE
nbdev_build_docs fails with NotImplementedError raised in asyncio

### ISSUE THREAD

**Issue by jnareb** [fastai/nbdev#327]
After upgrading all Python modules with `conda update --all`, the `nbdev_build_docs` now fails with the following error:

```
$ nbdev_build_docs
converting: C:\Users\jnare\GitHub\git-commit-graph-ext\index.ipynb

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 365, in _async_cleanup_kernel
    await ensure_async(self.kc.stop_channels())
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_client\client.py", line 125, in stop_channels
    if self.shell_channel.is_alive():
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_client\client.py", line 151, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_client\connect.py", line 561, in connect_shell
    return self._create_connected_socket('shell', identity=identity)
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_client\connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "c:\programdata\anaconda3\lib\site-packages\zmq\sugar\context.py", line 226, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\zmq\_future.py", line 144, in __init__
    self._init_io_state()
  File "c:\programdata\anaconda3\lib\site-packages\zmq\asyncio\__init__.py", line 53, in _init_io_state
    self.io_loop.add_reader(self._fd, lambda : self._handle_events(0, 0))
  File "c:\programdata\anaconda3\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError 
Exception ignored in: <function Socket.__del__ at 0x000002036B509160>
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
    self.close()
  File "c:\programdata\anaconda3\lib\site-packages\zmq\_future.py", line 160, in close
    self._clear_io_state()
  File "c:\programdata\anaconda3\lib\site-packages\zmq\asyncio\__init__.py", line 60, in _clear_io_state
    self.io_loop.remove_reader(self._fd)
  File "c:\programdata\anaconda3\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored in: <function Socket.__del__ at 0x000002036B509160>
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
    self.close()
  File "c:\programdata\anaconda3\lib\site-packages\zmq\_future.py", line 160, in close
    self._clear_io_state()
  File "c:\programdata\anaconda3\lib\site-packages\zmq\asyncio\__init__.py", line 60, in _clear_io_state
    self.io_loop.remove_reader(self._fd)
  File "c:\programdata\anaconda3\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError
NotImplementedError:
Conversion failed on the following:
index.ipynb
```

I use Python 3.8.5 (from Anaconda3), Jupyter Notebook 6.1.4, JupyterLab 2.2.6

The following version of libraries are currently installed:

- nbclient 0.5.1
- jupyter_client 6.1.7
- pyzmq 19.0.2
- nbdev 1.1.5

My operating system is Windows 10 Home 64-bit, version 1909

**Comment by jnareb** [comment]
It turns out that the same problem exists in `nbdev_test_nb` and was caused, from what I understand, by the **change in Python 3.8**, where the default event loop on **Windows** changed to `proactor` (and not "selector" event loop).

See for example issue mkdocs/mkdocs#1885 fixed in mkdocs/mkdocs#1922

It looks like for Windows one needs to add the following line

```python
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
