### ISSUE TITLE
Setting for ignoring cells that don't have "#export" in them?

### ISSUE THREAD

**Issue by aronchick** [fastai/nbdev#335]
If we have a notebook with three cells:
- export train
- export train
- (graphing script)

It'd be nice if there WAS an export, it acted on it, but if there wasn't (by default) it ignored it as though it was just another text cell.

Right now it does this:
```
Warning: Exporting to "train.py" but this module is not part of this build
Warning: Exporting to "train.py" but this module is not part of this build
Traceback (most recent call last):
[long stack trace...]
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by aronchick** [comment]
This is my mistake. I keep running into - 

```
Warning: Exporting to "train.py" but this module is not part of this build
Traceback (most recent call last):
  File "/home/daaronch/anaconda3/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/home/daaronch/anaconda3/lib/python3.8/site-packages/fastcore/script.py", line 103, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/daaronch/anaconda3/lib/python3.8/site-packages/nbdev/export2html.py", line 478, in nbdev_build_lib
    notebook2script(fname=fname)
  File "/home/daaronch/anaconda3/lib/python3.8/site-packages/nbdev/export.py", line 413, in notebook2script
    for f in sorted(files): d = _notebook2script(f, modules, silent=silent, to_dict=d)
  File "/home/daaronch/anaconda3/lib/python3.8/site-packages/nbdev/export.py", line 351, in _notebook2script
    if to_dict is None: _add2all(fname_out, [f"'{f}'" for f in names if '.' not in f and len(f) > 0] + extra)
  File "/home/daaronch/anaconda3/lib/python3.8/site-packages/nbdev/export.py", line 209, in _add2all
    start,end = re_all.start(),re_all.end()
AttributeError: 'NoneType' object has no attribute 'start'
```

And assumed it was because it was hitting cells that didn't have export in them. Don't know how to solve that though.

**Comment by aronchick** [comment]
The answer here appears to be `nbdev_build_lib` requires a notebook to run first that has `# default_exp <module_name>` in it. So create multiple notebooks, each named `00_create_foo` where the first (and only) line is `# default_exp foo`
