### ISSUE TITLE
nbdev_clean_nbs prevents launch of git mergetool

### ISSUE THREAD

**Issue by jcpayne** [fastai/nbdev#361]
Is this expected behavior?  If I run nbdev_clean_nbs, it executes correctly.  But when I try to merge a git conflict, nbdev_clean_nbs throws an error and prevents me from starting up git mergetool.  Also, the message says that no files need merging, but as you can see at the bottom, they do.  I tried reinstalling nbdev_install_git_hooks, but that didn't fix the problem.

% git mergetool
>Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/nbdev_clean_nbs", line 8, in <module>
    sys.exit(nbdev_clean_nbs())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbdev/clean.py", line 76, in nbdev_clean_nbs
    nb = json.load(input_stream)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2417 column 1 (char 1461444)
error: external filter 'nbdev_clean_nbs --read_input_stream True' failed 1
error: external filter 'nbdev_clean_nbs --read_input_stream True' failed
fatal: dev_nbs/trident_tz_on_vm.ipynb: clean filter 'clean-nbs' failed
No files need merging

% git pull
>error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by jcpayne** [comment]
I fixed this by deleting
- .git/hooks/post-merge
- .gitconfig
- .gitattributes
then running git commands (`git add`, `git commit`, and `git pull`), and then reinstalling `nbdev_install_git_hooks`.  Something was certainly wrong but perhaps not worth worrying about -- I'll leave it open for now so you can see the error message, but please feel free to close it.

**Comment by igorbrigadir** [comment]
#334 is related. I found out `nbdev_fix_merge` is a good command to try in this case.

**Comment by hamelsmu** [comment]
> I fixed this by deleting

Great closing this issue!
