### ISSUE TITLE
nbdev_build_docs fails with rpy2

### ISSUE THREAD

**Issue by nicole-brewer** [fastai/nbdev#362]
nbdev_build_lib works just fine.

The error comes from an rpy2 import, `from rpy2.robjects import packages` and eventually fails on the line `rpy2.rinterface.baseenv.get("show")`. I can successfully do the import, and the troublesome line in a notebook.

This leads me to think that there is something that is being excluded from the environment when `_notebook2html` is run with parallel, which I believe comes fastcore? The build fails on every notebook that directly or indirectly imports rpy2.robjects.packages

Any help would be appreciated.

```
An error occurred while executing the following cell:
------------------
from nbdev.showdoc import show_doc
from superpower_gui.custom_widgets.ratio import *
------------------

---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-1-be36ae09dae5> in <module>
      1 from nbdev.showdoc import show_doc
----> 2 from superpower_gui.custom_widgets.ratio import *

~/Repos/work/superpower_gui/nbs/superpower_gui/custom_widgets/ratio.py in <module>
     14
     15 # Cell
---> 16 from ..view.widgets import Button, Grid, Label, FloatText, IntText, Text, AlignedLabel, IntLabel, Dropdown
     17 from ..view.widget_collections import WidgetList, VBox, HBox, Box, WidgetContainer
     18 from ..model.model import Model

~/Repos/work/superpower_gui/nbs/superpower_gui/view/widgets.py in <module>
     11
     12 # Cell
---> 13 from ..rpy import Int, Float, IntArray, FloatArray
     14 from superpower_gui import rpy
     15 from ..model.model_collections import CollectionList, CollectionArray

~/Repos/work/superpower_gui/nbs/superpower_gui/rpy.py in <module>
      6 # Cell
      7 import rpy2
----> 8 from rpy2.robjects import packages
      9 from rpy2.robjects import numpy2ri
     10 from rpy2 import rinterface

~/miniconda3/lib/python3.7/site-packages/rpy2/robjects/__init__.py in <module>
     17 import rpy2.rlike.container as rlc
     18
---> 19 from rpy2.robjects.robject import RObjectMixin, RObject
     20 from rpy2.robjects.vectors import (BoolVector,
     21                                    IntVector,

~/miniconda3/lib/python3.7/site-packages/rpy2/robjects/robject.py in <module>
     50
     51
---> 52 class RObjectMixin(object):
     53     """ Class to provide methods common to all RObject instances. """
     54

~/miniconda3/lib/python3.7/site-packages/rpy2/robjects/robject.py in RObjectMixin()
     64     __rclass = rpy2.rinterface.baseenv.get("class")
     65     __rclass_set = rpy2.rinterface.baseenv.get("class<-")
---> 66     __show = rpy2.rinterface.baseenv.get("show")
     67
     68     __slots = None

LookupError: 'show' not found
LookupError: 'show' not found

'HTMLExporter' object has no attribute 'template_path'
Traceback (most recent call last):
  File "/Users/nicolebrewer/miniconda3/bin/nbdev_build_docs", line 10, in <module>
    sys.exit(nbdev_build_docs())
  File "/Users/nicolebrewer/miniconda3/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/Users/nicolebrewer/miniconda3/lib/python3.7/site-packages/nbdev/cli.py", line 221, in nbdev_build_docs
    notebook2html(fname=fname, force_all=force_all, n_workers=n_workers, pause=pause)
  File "/Users/nicolebrewer/miniconda3/lib/python3.7/site-packages/nbdev/export2html.py", line 582, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
```

**Comment by hamelsmu** [comment]
Hello @nicole-brewer are you getting errors only with r2py? are you able to successfully use nbdev without this import?  

Also might be helpful if you shared your notebook and project for reproducibility of the error.  Thank you

**Comment by hamelsmu** [comment]
Closing b/c no comment or clarification from OP, issue is stale.
