### ISSUE TITLE
nbdev_build_docs failure on markdown.tpl

### ISSUE THREAD

**Issue by andaag** [fastai/nbdev#46]
```
# nbdev_build_docs
converting: /home/neuron/src/sch/p10n-experiments-nbdev/02_yapoexperiment.ipynb
basic.tpl
Traceback (most recent call last):
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/nbdev/cli.py", line 158, in nbdev_build_docs
    if mk_readme: make_readme()
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/nbdev/cli.py", line 145, in make_readme
    convert_md(index_fn, Config().config_file.parent, jekyll=False)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/nbdev/export2html.py", line 408, in convert_md
    export = exp.from_notebook_node(nb, resources=meta_jekyll)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 357, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/neuron/src/sch/p10n-experiments-nbdev/.venv/lib/python3.6/site-packages/nbdev/templates/md.tpl", line 1, in top-level template code
    {%- extends 'markdown.tpl' -%}{% block body %}
jinja2.exceptions.TemplateNotFound: markdown.tpl
```

At first glance looks like a duplicate of https://github.com/fastai/nbdev/issues/8, but I'm using nbdev 0.2.5.

```
# find . -name markdown.tpl
./.venv/lib/python3.6/site-packages/nbconvert/templates/markdown.tpl
```

**Comment by andaag** [comment]
This is pipenv installed, using python 3.6.9.

**Comment by sgugger** [comment]
It's not a duplicate of #8 as this file is not provided by us but nbconvert. Can you check you have the latest version of that module?

**Comment by andaag** [comment]
I do, a bit too latest version, I was on a prerelease of nbconvert. Sorry about the noise!

(this breaks with nbconvert 6.0.0a)
