### ISSUE TITLE
Conda Release Fails with fastcore.basics.HTTP404NotFoundError

### ISSUE THREAD

**Issue by kheyer** [fastai/nbdev#511]
nbdev version 1.1.4 conda install

When running `make release`, the pip package builds fine, but the Conda package fails with the following error trace. The same error arrises from `make conda_release`. Am I missing a dependency or something?

```
fastrelease_conda_package
Traceback (most recent call last):
  File "/home/dmai/miniconda3/envs/mrl/bin/fastrelease_conda_package", line 10, in <module>
    sys.exit(fastrelease_conda_package())
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastrelease/conda.py", line 158, in fastrelease_conda_package
    write_conda_meta(path)
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastrelease/conda.py", line 137, in write_conda_meta
    _write_yaml(path, *_get_conda_meta())
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastrelease/conda.py", line 110, in _get_conda_meta
    pypi = pypi_json(f'{name}/{ver}')
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastrelease/conda.py", line 21, in pypi_json
    return urljson(f'{_PYPI_URL}{s}/json')
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastcore/net.py", line 122, in urljson
    res = urlread(url, data=data)
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastcore/net.py", line 112, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
fastcore.basics.HTTP404NotFoundError: HTTP Error 404: Not Found
make: *** [Makefile:28: conda_release] Error 1
```

**Comment by kheyer** [comment]
I partially figured out the issue. My package name was already taken on pypi. Following [this post](https://forums.fast.ai/t/nbdev-how-do-i-change-the-name-of-the-pypi-package-if-the-name-of-my-project-is-already-taken-on-pypi/69842/2) I changed the package name in `setup.py` to `{package_name}-pypi`. When  `pypi_json` tried to look for the package, it searched for `{package_name}` instead of `{package_name}-pypi`. This caused the above error.

I've now changed the `lib_name` value in `settings.ini` to `{package_name}-lib` just to get around the name taken issue. 

Now trying to build the conda package gives the following error:

```
fastrelease_conda_package
Traceback (most recent call last):
  File "/home/dmai/miniconda3/envs/mrl/bin/fastrelease_conda_package", line 10, in <module>
    sys.exit(fastrelease_conda_package())
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastrelease/conda.py", line 168, in fastrelease_conda_package
    res = run(f"conda {build} --no-anaconda-upload {build_args} {name}")
  File "/home/dmai/miniconda3/envs/mrl/lib/python3.7/site-packages/fastcore/xtras.py", line 184, in run
    if res.returncode: raise IOError(stdout)
OSError
make: *** [Makefile:28: conda_release] Error 1
```

**Comment by kheyer** [comment]
Okay so the above was caused by the fact that the conda build was trying to import `{package_name}-lib` which was failing. Here's a solution I've worked out so far:

1. Update settings to have different names for lib vs pypi

```
lib_name = mrl
pypi_name = mrl-pypi
```

2. Update `setup.py`

```
name = cfg['lib_name'] --> name = cfg['pypi_name']
```

3. Build pypi package

```
make pypi
```

4. Update some `fastrelease` code to deal with lib name vs pypi name 

```
from fastcore.script import *
from fastcore.all import *
from fastrelease.core import find_config

import yaml,subprocess,glob,platform
from copy import deepcopy
try: from packaging.version import parse
except ImportError: from pip._vendor.packaging.version import parse

_PYPI_URL = 'https://pypi.org/pypi/'

def pypi_json(s):
    "Dictionary decoded JSON for PYPI path `s`"
    return urljson(f'{_PYPI_URL}{s}/json')

def as_posix(p):
    "`Path(p).as_posix()`"
    return Path(p).as_posix()

def _get_conda_meta():
    cfg,cfg_path = find_config()
    name,ver = cfg.get('lib_name'),cfg.get('version')
    pypi_name = cfg.get('pypi_name')
    url = cfg.get('doc_host') or cfg.get('git_url')

    reqs = ['pip', 'python', 'packaging']
    if cfg.get('requirements'): reqs += cfg.get('requirements').split()
    if cfg.get('conda_requirements'): reqs += cfg.get('conda_requirements').split()

    pypi = pypi_json(f'{pypi_name}/{ver}')
    rel = [o for o in pypi['urls'] if o['packagetype']=='sdist'][0]

    # Work around conda build bug - 'package' and 'source' must be first
    d1 = {
        'package': {'name': name, 'version': ver},
        'source': {'url':rel['url'], 'sha256':rel['digests']['sha256']}
    }

    d2 = {
        'build': {'number': '0', 'noarch': 'python',
                  'script': '{{ PYTHON }} -m pip install . -vv'},
        'requirements': {'host':reqs, 'run':reqs},
        'test': {'imports': [cfg.get('lib_path')]},
        'about': {
            'license': 'Apache Software',
            'license_family': 'APACHE',
            'home': url, 'doc_url': url, 'dev_url': url,
            'summary': cfg.get('description')
        },
        'extra': {'recipe-maintainers': [cfg.get('user')]}
    }
    return name,d1,d2

def write_conda_meta(path='conda'):
    "Writes a `meta.yaml` file to the `conda` directory of the current directory"
    _write_yaml(path, *_get_conda_meta())

def _write_yaml(path, name, d1, d2):
    path = Path(path)
    p = path/name
    p.mkdir(exist_ok=True, parents=True)
    yaml.SafeDumper.ignore_aliases = lambda *args : True
    with (p/'meta.yaml').open('w') as f:
        yaml.safe_dump(d1, f)
        yaml.safe_dump(d2, f)

def conda_output_path(name,ver):
    "Output path for conda build"
    pre = run('conda info --root').strip()
    s = f"{as_posix(pre)}/conda-bld/*/{name}-{ver}-py"
    res = first(glob.glob(f"{s}_0.tar.bz2"))
    if not res:
        pyver = strcat(sys.version_info[:2])
        res = first(glob.glob(f"{s}{pyver}_0.tar.bz2"))
    return as_posix(res)

def anaconda_upload(name, version, user=None, token=None, env_token=None):
    "Update `name` `version` to anaconda"
    user = f'-u {user} ' if user else ''
    if env_token: token = os.getenv(env_token)
    token = f'-t {token} ' if token else ''
    return run(f'anaconda {token} upload {user} {conda_output_path(name,version)} --skip-existing', stderr=True)

if __name__ == "__main__":
    path = 'conda'
    write_conda_meta(path)

```

5.  change directory to `{package_name}/conda` and run conda build in the terminal. Include conda channels if necessary

```
conda build --no-anaconda-upload {package_name}
```

6. Run conda upload command in terminal
