### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by kwhkim** [fastai/nbdev#519]
Hello, 

 I get error doing `dev_nb2md filename`.

 Here's what i got.

```
$ nbdev_nb2md EDA2.ipynb
Traceback (most recent call last):
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\Scripts\nbdev_nb2md-script.py", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_nb2md')())
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\lib\site-packages\fastcore\script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "d:\git\nbdev\nbdev\export2html.py", line 653, in nbdev_nb2md
    _nbdev_detach(fname, dest=img_path)
  File "d:\git\nbdev\nbdev\export2html.py", line 601, in _nbdev_detach
    j = json.load(path_nb.open())
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 478: illegal multibyte sequence
```

could you tell me what's wrong?

**Comment by kwhkim** [comment]
Since the error message points to codec, 

I edited `_nbdev_detach()` from `export2html.py`.

I changed `j=json.load(path_nb.open())` to `j = json.load(path_nb.open(encoding ='utf-8'))`.

And I get different error and it goes like the below

```
$ nbdev_nb2md EDA2.ipynb
Traceback (most recent call last):
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\Scripts\nbdev_nb2md-script.py", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_nb2md')())
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\lib\site-packages\fastcore\script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "d:\git\nbdev\nbdev\export2html.py", line 654, in nbdev_nb2md
    convert_md(fname, dest, jekyll=jekyll, img_path=img_path)
  File "d:\git\nbdev\nbdev\export2html.py", line 548, in convert_md
    nb['cells'] = [compose(partial(adapt_img_path, fname=fname, dest=dest_path, jekyll=jekyll), *process_cell)(c)
  File "d:\git\nbdev\nbdev\export2html.py", line 548, in <listcomp>
    nb['cells'] = [compose(partial(adapt_img_path, fname=fname, dest=dest_path, jekyll=jekyll), *process_cell)(c)
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\lib\site-packages\fastcore\basics.py", line 676, in _inner
    for f in funcs: x = f(x, *args, **kwargs)
  File "d:\git\nbdev\nbdev\export2html.py", line 120, in add_jekyll_notes
    styles = get_config().get('jekyll_styles', 'note,warning,tip,important').split(',')
  File "d:\git\nbdev\nbdev\imports.py", line 29, in get_config
    config = Config(cfg_path, cfg_name=cfg_name)
  File "C:\Users\Home\miniconda3\envs\rtopython2-pip\lib\site-packages\fastcore\foundation.py", line 259, in __init__
    else: raise Exception(f"Could not find {cfg_name}")
Exception: Could not find settings.ini
```

I just wanted to test what's written in this [blog](https://www.fast.ai/2020/01/20/nb2md/)

but I guess `nbdev` needs configuration step or do i need to read through tutorial?

but the example `settings.ini` shows nothing about encoding so

the problem about encoding is still relevant i think even if i need configuration step i guess

**Comment by jph00** [comment]
Try asking on forums.fast.ai
