### ISSUE TITLE
Running nbdev_build_lib generates FileNotFoundError

### ISSUE THREAD

**Issue by dustinvanstee** [fastai/nbdev#52]
Here is my sequence .
1.  I generate my project from the github template, 
2. clone my project to my local machine 
3. edit my settings.ini file with my project meta data
4. run nbdev_build_lib

When I run nbdev_build_lib i get this error. 

nbdev_build_lib
Traceback (most recent call last):
  File "/gpfs/home/s4s004/vanstee/anaconda3/envs/powerai-1.6.2/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/gpfs/home/s4s004/vanstee/anaconda3/envs/powerai-1.6.2/lib/python3.7/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/gpfs/home/s4s004/vanstee/anaconda3/envs/powerai-1.6.2/lib/python3.7/site-packages/nbdev/cli.py", line 20, in nbdev_build_lib
    notebook2script(fname=fname)
  File "/gpfs/home/s4s004/vanstee/anaconda3/envs/powerai-1.6.2/lib/python3.7/site-packages/nbdev/export.py", line 364, in notebook2script
    update_baseurl()
  File "/gpfs/home/s4s004/vanstee/anaconda3/envs/powerai-1.6.2/lib/python3.7/site-packages/nbdev/export.py", line 351, in update_baseurl
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/s4s004/vanstee/2019-10-kaggle-fastai/2020-01-pku/docs/_config.yml'

As a workaround, I just touch the docs/_config.yml file and I am able to get past this issue.

**Comment by sgugger** [comment]
Are you sure this is on the latest version? We had that bug but it has normally been fixed.

**Comment by dustinvanstee** [comment]
Thank-you, I was on 0.2.4 and upgraded to 0.2.7 .  Now it works.  Appreciate it!

**Comment by HDavidEspinosa** [comment]
Conda package still downloads 0.2.4 same for pip. How do I get nbdev0.2.7?
