### ISSUE TITLE
nbdev_update_lib throws error when --fname specified

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [fastai/nbdev#525]
# Setup

```bash
$ tree /tmp/test-nbdev/
/tmp/test-nbdev/
├── notebooks
│   └── module
│       └── file.ipynb
└── settings.ini

2 directories, 2 files
```

setting.ini

```ini
[DEFAULT]
host = gitlab
lib_name = projectname
company_name = company
user = user
description = Is a foo a bar
author = company
author_email = company@company.com
copyright = company
branch = master
version = 0.0.1
min_python = 3.6
audience = Developers
language = English
custom_sidebar = False
license = apache2
status = 2
nbs_path = notebooks/**/*
doc_path = docs
recursive = False
url = /
doc_host = %(url)s
doc_baseurl = /repo
lib_path = %(lib_name)s
title = %(lib_name)s
lib_folder = /tmp/test-nbdev
git_url = test-nbdev
```

`file.ipynb` can be seen in the attached screenshot:

<img width="359" alt="Screen Shot 2021-09-03 at 10 47 07 AM" src="https://user-images.githubusercontent.com/6334199/132024625-90509516-ac91-42c6-80ad-dacb9557edf8.png">

# Action taken

Making the following change to the auto generated file `file.py`:
```diff
$ git diff projectname/module/file.py
diff --git a/projectname/module/file.py b/projectname/module/file.py
index b7d61d7..7a13c29 100644
--- a/projectname/module/file.py
+++ b/projectname/module/file.py
@@ -4,4 +4,4 @@ __all__ = []
 
 # Cell
 
-print('foobar')
\ No newline at end of file
+print('foobaz')
\ No newline at end of file
```

# Expected outcome

Running `nbdev_update_lib` to update `file.ipynb` with new print function

# Actual outcome

Running `nbdev_update_lib` produces no output:

```bash
$ nbdev_update_lib 
```

and when I provide the flag `--fname` it throws the following error:
```bash
$ nbdev_update_lib --fname projectname/module/file.py 
Traceback (most recent call last):
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/bin/nbdev_update_lib", line 8, in <module>
    sys.exit(nbdev_update_lib())
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/nbdev/sync.py", line 132, in nbdev_update_lib
    files = files.filter(lambda x: str(x.relative_to(Config().path("lib_path"))) in exported)
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/fastcore/foundation.py", line 157, in filter
    return self._new(filter_ex(self, f=f, negate=negate, gen=gen, **kwargs))
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/fastcore/basics.py", line 529, in filter_ex
    return list(res)
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/nbdev/sync.py", line 132, in <lambda>
    files = files.filter(lambda x: str(x.relative_to(Config().path("lib_path"))) in exported)
  File "/Users/user.name/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/pathlib.py", line 883, in relative_to
    .format(str(self), str(formatted)))
ValueError: 'projectname/module/file.py' does not start with '/private/tmp/test-nbdev/projectname'
```

**Comment by benoit-cty** [comment]
Hello,
You provide a wrong path.
You have to use `nbdev_update_lib --fname notebooks/module/file.py`
