### ISSUE TITLE
make release generates pypi new version but fails with building conda OSError make: *** [conda_release] Error 1

### ISSUE THREAD

**Issue by oguiza** [fastai/nbdev#526]
Hi,

I've been using nbdev for some time and it works great. I've built my own library (timeseriesAI/tsai) using nbdev, and have released many pip versions. It's always worked great the first time when using make pypi. 
However, I wanted to release my code in conda, but I'm having an issue when I try `make release`. The pip release part goes well, but the conda release is where I get the issues. 

Here's the full stack trace: 

```
(py37) ➜  tsai git:(main) make release
rm -rf dist
python setup.py sdist bdist_wheel
running sdist
running egg_info
writing tsai.egg-info/PKG-INFO
writing dependency_links to tsai.egg-info/dependency_links.txt
writing entry points to tsai.egg-info/entry_points.txt
writing requirements to tsai.egg-info/requires.txt
writing top-level names to tsai.egg-info/top_level.txt
reading manifest file 'tsai.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'tsai.egg-info/SOURCES.txt'
running check
creating tsai-0.2.19
creating tsai-0.2.19/tsai
creating tsai-0.2.19/tsai.egg-info
creating tsai-0.2.19/tsai/callback
creating tsai-0.2.19/tsai/data
creating tsai-0.2.19/tsai/models
copying files to tsai-0.2.19...
copying CONTRIBUTING.md -> tsai-0.2.19
copying LICENSE -> tsai-0.2.19
copying MANIFEST.in -> tsai-0.2.19
copying README.md -> tsai-0.2.19
copying settings.ini -> tsai-0.2.19
copying setup.py -> tsai-0.2.19
copying tsai/__init__.py -> tsai-0.2.19/tsai
copying tsai/_nbdev.py -> tsai-0.2.19/tsai
copying tsai/all.py -> tsai-0.2.19/tsai
copying tsai/imports.py -> tsai-0.2.19/tsai
copying tsai/learner.py -> tsai-0.2.19/tsai
copying tsai/losses.py -> tsai-0.2.19/tsai
copying tsai/metrics.py -> tsai-0.2.19/tsai
copying tsai/optimizer.py -> tsai-0.2.19/tsai
copying tsai/tslearner.py -> tsai-0.2.19/tsai
copying tsai/tutorials.py -> tsai-0.2.19/tsai
copying tsai/utils.py -> tsai-0.2.19/tsai
copying tsai.egg-info/PKG-INFO -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/SOURCES.txt -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/dependency_links.txt -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/entry_points.txt -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/not-zip-safe -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/requires.txt -> tsai-0.2.19/tsai.egg-info
copying tsai.egg-info/top_level.txt -> tsai-0.2.19/tsai.egg-info
copying tsai/callback/MVP.py -> tsai-0.2.19/tsai/callback
copying tsai/callback/PredictionDynamics.py -> tsai-0.2.19/tsai/callback
copying tsai/callback/__init__.py -> tsai-0.2.19/tsai/callback
copying tsai/callback/all.py -> tsai-0.2.19/tsai/callback
copying tsai/callback/core.py -> tsai-0.2.19/tsai/callback
copying tsai/callback/noisy_student.py -> tsai-0.2.19/tsai/callback
copying tsai/data/__init__.py -> tsai-0.2.19/tsai/data
copying tsai/data/all.py -> tsai-0.2.19/tsai/data
copying tsai/data/core.py -> tsai-0.2.19/tsai/data
copying tsai/data/external.py -> tsai-0.2.19/tsai/data
copying tsai/data/features.py -> tsai-0.2.19/tsai/data
copying tsai/data/image.py -> tsai-0.2.19/tsai/data
copying tsai/data/metadatasets.py -> tsai-0.2.19/tsai/data
copying tsai/data/mixed.py -> tsai-0.2.19/tsai/data
copying tsai/data/mixed_augmentation.py -> tsai-0.2.19/tsai/data
copying tsai/data/preparation.py -> tsai-0.2.19/tsai/data
copying tsai/data/preprocessing.py -> tsai-0.2.19/tsai/data
copying tsai/data/tabular.py -> tsai-0.2.19/tsai/data
copying tsai/data/transforms.py -> tsai-0.2.19/tsai/data
copying tsai/data/unwindowed.py -> tsai-0.2.19/tsai/data
copying tsai/data/validation.py -> tsai-0.2.19/tsai/data
copying tsai/models/FCN.py -> tsai-0.2.19/tsai/models
copying tsai/models/FCNPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/InceptionTime.py -> tsai-0.2.19/tsai/models
copying tsai/models/InceptionTimePlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/MINIROCKET.py -> tsai-0.2.19/tsai/models
copying tsai/models/MINIROCKETPlus_Pytorch.py -> tsai-0.2.19/tsai/models
copying tsai/models/MINIROCKET_Pytorch.py -> tsai-0.2.19/tsai/models
copying tsai/models/MLP.py -> tsai-0.2.19/tsai/models
copying tsai/models/MultiInputNet.py -> tsai-0.2.19/tsai/models
copying tsai/models/OmniScaleCNN.py -> tsai-0.2.19/tsai/models
copying tsai/models/RNN.py -> tsai-0.2.19/tsai/models
copying tsai/models/RNNPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/RNN_FCN.py -> tsai-0.2.19/tsai/models
copying tsai/models/RNN_FCNPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/ROCKET.py -> tsai-0.2.19/tsai/models
copying tsai/models/ResCNN.py -> tsai-0.2.19/tsai/models
copying tsai/models/ResNet.py -> tsai-0.2.19/tsai/models
copying tsai/models/ResNetPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/TCN.py -> tsai-0.2.19/tsai/models
copying tsai/models/TSPerceiver.py -> tsai-0.2.19/tsai/models
copying tsai/models/TST.py -> tsai-0.2.19/tsai/models
copying tsai/models/TSTPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/TSiTPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/TabFusionTransformer.py -> tsai-0.2.19/tsai/models
copying tsai/models/TabModel.py -> tsai-0.2.19/tsai/models
copying tsai/models/TabTransformer.py -> tsai-0.2.19/tsai/models
copying tsai/models/TransformerModel.py -> tsai-0.2.19/tsai/models
copying tsai/models/XCM.py -> tsai-0.2.19/tsai/models
copying tsai/models/XCMPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/XResNet1d.py -> tsai-0.2.19/tsai/models
copying tsai/models/XResNet1dPlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/XceptionTime.py -> tsai-0.2.19/tsai/models
copying tsai/models/XceptionTimePlus.py -> tsai-0.2.19/tsai/models
copying tsai/models/__init__.py -> tsai-0.2.19/tsai/models
copying tsai/models/all.py -> tsai-0.2.19/tsai/models
copying tsai/models/explainability.py -> tsai-0.2.19/tsai/models
copying tsai/models/layers.py -> tsai-0.2.19/tsai/models
copying tsai/models/mWDN.py -> tsai-0.2.19/tsai/models
copying tsai/models/misc.py -> tsai-0.2.19/tsai/models
copying tsai/models/utils.py -> tsai-0.2.19/tsai/models
Writing tsai-0.2.19/setup.cfg
creating dist
Creating tar archive
removing 'tsai-0.2.19' (and everything under it)
running bdist_wheel
running build
running build_py
copying tsai/metrics.py -> build/lib/tsai
copying tsai/tutorials.py -> build/lib/tsai
copying tsai/_nbdev.py -> build/lib/tsai
copying tsai/__init__.py -> build/lib/tsai
copying tsai/utils.py -> build/lib/tsai
copying tsai/optimizer.py -> build/lib/tsai
copying tsai/losses.py -> build/lib/tsai
copying tsai/tslearner.py -> build/lib/tsai
copying tsai/learner.py -> build/lib/tsai
copying tsai/models/TSPerceiver.py -> build/lib/tsai/models
copying tsai/models/OmniScaleCNN.py -> build/lib/tsai/models
copying tsai/models/misc.py -> build/lib/tsai/models
copying tsai/models/RNN_FCN.py -> build/lib/tsai/models
copying tsai/models/ResNetPlus.py -> build/lib/tsai/models
copying tsai/models/FCNPlus.py -> build/lib/tsai/models
copying tsai/models/FCN.py -> build/lib/tsai/models
copying tsai/models/TransformerModel.py -> build/lib/tsai/models
copying tsai/models/XResNet1d.py -> build/lib/tsai/models
copying tsai/models/XceptionTimePlus.py -> build/lib/tsai/models
copying tsai/models/TCN.py -> build/lib/tsai/models
copying tsai/models/TabModel.py -> build/lib/tsai/models
copying tsai/models/MINIROCKET_Pytorch.py -> build/lib/tsai/models
copying tsai/models/all.py -> build/lib/tsai/models
copying tsai/models/MLP.py -> build/lib/tsai/models
copying tsai/models/XResNet1dPlus.py -> build/lib/tsai/models
copying tsai/models/TSiTPlus.py -> build/lib/tsai/models
copying tsai/models/MINIROCKET.py -> build/lib/tsai/models
copying tsai/models/ResNet.py -> build/lib/tsai/models
copying tsai/models/TabTransformer.py -> build/lib/tsai/models
copying tsai/models/utils.py -> build/lib/tsai/models
copying tsai/models/RNN_FCNPlus.py -> build/lib/tsai/models
copying tsai/models/InceptionTime.py -> build/lib/tsai/models
copying tsai/models/TSTPlus.py -> build/lib/tsai/models
copying tsai/models/XCMPlus.py -> build/lib/tsai/models
copying tsai/models/ResCNN.py -> build/lib/tsai/models
copying tsai/models/XCM.py -> build/lib/tsai/models
copying tsai/models/TST.py -> build/lib/tsai/models
copying tsai/models/InceptionTimePlus.py -> build/lib/tsai/models
copying tsai/models/RNNPlus.py -> build/lib/tsai/models
copying tsai/models/mWDN.py -> build/lib/tsai/models
copying tsai/models/layers.py -> build/lib/tsai/models
copying tsai/models/explainability.py -> build/lib/tsai/models
copying tsai/models/XceptionTime.py -> build/lib/tsai/models
copying tsai/models/MultiInputNet.py -> build/lib/tsai/models
copying tsai/models/RNN.py -> build/lib/tsai/models
copying tsai/models/MINIROCKETPlus_Pytorch.py -> build/lib/tsai/models
copying tsai/models/ROCKET.py -> build/lib/tsai/models
copying tsai/models/TabFusionTransformer.py -> build/lib/tsai/models
copying tsai/callback/core.py -> build/lib/tsai/callback
copying tsai/callback/all.py -> build/lib/tsai/callback
copying tsai/callback/PredictionDynamics.py -> build/lib/tsai/callback
copying tsai/callback/MVP.py -> build/lib/tsai/callback
copying tsai/callback/noisy_student.py -> build/lib/tsai/callback
copying tsai/data/transforms.py -> build/lib/tsai/data
copying tsai/data/tabular.py -> build/lib/tsai/data
copying tsai/data/unwindowed.py -> build/lib/tsai/data
copying tsai/data/features.py -> build/lib/tsai/data
copying tsai/data/core.py -> build/lib/tsai/data
copying tsai/data/mixed.py -> build/lib/tsai/data
copying tsai/data/mixed_augmentation.py -> build/lib/tsai/data
copying tsai/data/preprocessing.py -> build/lib/tsai/data
copying tsai/data/metadatasets.py -> build/lib/tsai/data
copying tsai/data/external.py -> build/lib/tsai/data
copying tsai/data/image.py -> build/lib/tsai/data
copying tsai/data/preparation.py -> build/lib/tsai/data
copying tsai/data/validation.py -> build/lib/tsai/data
installing to build/bdist.macosx-10.9-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.9-x86_64/wheel
creating build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/metrics.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/tutorials.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/_nbdev.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
creating build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TSPerceiver.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/OmniScaleCNN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/misc.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/RNN_FCN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/ResNetPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/FCNPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/FCN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TransformerModel.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XResNet1d.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XceptionTimePlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TCN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TabModel.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/MINIROCKET_Pytorch.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/all.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/MLP.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XResNet1dPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TSiTPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/MINIROCKET.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/ResNet.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TabTransformer.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/utils.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/RNN_FCNPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/InceptionTime.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TSTPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XCMPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/ResCNN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XCM.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TST.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/InceptionTimePlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/RNNPlus.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/mWDN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/layers.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/explainability.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/XceptionTime.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/MultiInputNet.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/RNN.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/MINIROCKETPlus_Pytorch.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/ROCKET.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/models/TabFusionTransformer.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/models
copying build/lib/tsai/all.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/imports.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/utils.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/optimizer.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
copying build/lib/tsai/losses.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
creating build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/gblend.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/core.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/all.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/PredictionDynamics.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/MVP.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/callback/noisy_student.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/callback
copying build/lib/tsai/tslearner.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
creating build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/transforms.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/tabular.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/unwindowed.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/features.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/core.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/all.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/mixed.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/mixed_augmentation.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/preprocessing.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/metadatasets.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/external.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/image.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/preparation.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/data/validation.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai/data
copying build/lib/tsai/learner.py -> build/bdist.macosx-10.9-x86_64/wheel/tsai
running install_egg_info
Copying tsai.egg-info to build/bdist.macosx-10.9-x86_64/wheel/tsai-0.2.19-py3.7.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-10.9-x86_64/wheel/tsai-0.2.19.dist-info/WHEEL
creating 'dist/tsai-0.2.19-py3-none-any.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
adding 'tsai/__init__.py'
adding 'tsai/_nbdev.py'
adding 'tsai/all.py'
adding 'tsai/imports.py'
adding 'tsai/learner.py'
adding 'tsai/losses.py'
adding 'tsai/metrics.py'
adding 'tsai/optimizer.py'
adding 'tsai/tslearner.py'
adding 'tsai/tutorials.py'
adding 'tsai/utils.py'
adding 'tsai/callback/MVP.py'
adding 'tsai/callback/PredictionDynamics.py'
adding 'tsai/callback/__init__.py'
adding 'tsai/callback/all.py'
adding 'tsai/callback/core.py'
adding 'tsai/callback/gblend.py'
adding 'tsai/callback/noisy_student.py'
adding 'tsai/data/__init__.py'
adding 'tsai/data/all.py'
adding 'tsai/data/core.py'
adding 'tsai/data/external.py'
adding 'tsai/data/features.py'
adding 'tsai/data/image.py'
adding 'tsai/data/metadatasets.py'
adding 'tsai/data/mixed.py'
adding 'tsai/data/mixed_augmentation.py'
adding 'tsai/data/preparation.py'
adding 'tsai/data/preprocessing.py'
adding 'tsai/data/tabular.py'
adding 'tsai/data/transforms.py'
adding 'tsai/data/unwindowed.py'
adding 'tsai/data/validation.py'
adding 'tsai/models/FCN.py'
adding 'tsai/models/FCNPlus.py'
adding 'tsai/models/InceptionTime.py'
adding 'tsai/models/InceptionTimePlus.py'
adding 'tsai/models/MINIROCKET.py'
adding 'tsai/models/MINIROCKETPlus_Pytorch.py'
adding 'tsai/models/MINIROCKET_Pytorch.py'
adding 'tsai/models/MLP.py'
adding 'tsai/models/MultiInputNet.py'
adding 'tsai/models/OmniScaleCNN.py'
adding 'tsai/models/RNN.py'
adding 'tsai/models/RNNPlus.py'
adding 'tsai/models/RNN_FCN.py'
adding 'tsai/models/RNN_FCNPlus.py'
adding 'tsai/models/ROCKET.py'
adding 'tsai/models/ResCNN.py'
adding 'tsai/models/ResNet.py'
adding 'tsai/models/ResNetPlus.py'
adding 'tsai/models/TCN.py'
adding 'tsai/models/TSPerceiver.py'
adding 'tsai/models/TST.py'
adding 'tsai/models/TSTPlus.py'
adding 'tsai/models/TSiTPlus.py'
adding 'tsai/models/TabFusionTransformer.py'
adding 'tsai/models/TabModel.py'
adding 'tsai/models/TabTransformer.py'
adding 'tsai/models/TransformerModel.py'
adding 'tsai/models/XCM.py'
adding 'tsai/models/XCMPlus.py'
adding 'tsai/models/XResNet1d.py'
adding 'tsai/models/XResNet1dPlus.py'
adding 'tsai/models/XceptionTime.py'
adding 'tsai/models/XceptionTimePlus.py'
adding 'tsai/models/__init__.py'
adding 'tsai/models/all.py'
adding 'tsai/models/explainability.py'
adding 'tsai/models/layers.py'
adding 'tsai/models/mWDN.py'
adding 'tsai/models/misc.py'
adding 'tsai/models/utils.py'
adding 'tsai-0.2.19.dist-info/LICENSE'
adding 'tsai-0.2.19.dist-info/METADATA'
adding 'tsai-0.2.19.dist-info/WHEEL'
adding 'tsai-0.2.19.dist-info/entry_points.txt'
adding 'tsai-0.2.19.dist-info/top_level.txt'
adding 'tsai-0.2.19.dist-info/RECORD'
removing build/bdist.macosx-10.9-x86_64/wheel
twine upload --repository pypi dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading tsai-0.2.19-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 184k/184k [00:02<00:00, 82.4kB/s]
Uploading tsai-0.2.19.tar.gz
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147k/147k [00:01<00:00, 80.6kB/s]

View at:
https://pypi.org/project/tsai/0.2.19/
fastrelease_conda_package
Traceback (most recent call last):
  File "/Users/nacho/anaconda3/envs/py37/bin/fastrelease_conda_package", line 8, in <module>
    sys.exit(fastrelease_conda_package())
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastcore/script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastrelease/conda.py", line 165, in fastrelease_conda_package
    res = run(f"conda {build} --no-anaconda-upload {build_args} {name}")
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastcore/xtras.py", line 219, in run
    if res.returncode: raise IOError(stdout)
OSError
make: *** [conda_release] Error 1
```

My computer setup is this: 

python         : 3.7.6
tsai               : 0.2.19
fastai            : 2.5.2
fastcore       : 1.3.26
torch            : 1.8.1

I'd really appreciate it if anyone could help me with this issue. Thanks a lot!!

**Comment by muellerzr** [comment]
There's a few of these. I'm not sure where we go from here, I've pinged Jeremy on it because he's done this multiple times w/o issue

https://github.com/fastai/fastrelease/issues/58

https://github.com/fastai/fastrelease/issues/46

This may be promising?

https://github.com/fastai/nbdev/issues/511

**Comment by oguiza** [comment]
Hi @muellerzr and  for following up on this!!
I have to say I made it work in the end, but I tried so many things I'm not sure which one fixed it to be hones with you. 
I think it was this: 

user in you repo settings.ini == username in pypi.org == username in Anaconda.org == username in .pypirc in root dir
lib_name in you repo settings.ini == project name in pypi.org == package name in Anaconda.org == username in .pypirc in root dir
password in pypi.org == password in Anaconda.org == password in .pypirc
[pypi]
username = your_username
password = your_password

I got it to create a tsai release in conda. Unfortunately, it's super slow to install :(
I haven't been able to spend more time trying to get a speed up. 
I can close the issue if you want, or do you prefer to leave it until the solution is confirmed to work?

**Comment by muellerzr** [comment]
Let's leave it open until I can test it :) Glad you got it working!

**Comment by michaelaye** [comment]
I guess then in my case it doesn't work because I need to have project and library/package name different? (Overlapping work with older version of project, to be replaced by nbdev version)?
