### ISSUE TITLE
nbdev_build_lib error: Config() missing 2 arguments

### ISSUE THREAD

**Issue by AndreasVaage** [fastai/nbdev#561]
While following the [general tutorial](https://nbdev.fast.ai/tutorial.html), installing with conda, nbdev_build_lib exists with traceback: 
```
Traceback (most recent call last):
  File "/home/andreas/anaconda3/envs/wp3/bin/nbdev_build_lib", line 10, in <module>
    sys.exit(nbdev_build_lib())
  File "/home/andreas/anaconda3/envs/wp3/lib/python3.8/site-packages/fastcore/script.py", line 107, in _f 
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/andreas/anaconda3/envs/wp3/lib/python3.8/site-packages/nbdev/export2html.py", line 477, in nbdev_build_lib
    write_tmpls()
  File "/home/andreas/anaconda3/envs/wp3/lib/python3.8/site-packages/nbdev/export2html.py", line 467, in write_tmpls
    cfg = Config()
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'
```

Im running 
ubuntu 18.04
conda 4.10.3
python 3.8.6
fastcore 1.3.26
nbdev 1.1.5

**Comment by AndreasVaage** [comment]
I notice it is an old nbdev version. This was the one Conda installed by default and it does not allow me to update it in my current env. Ill make a new clean env and see.

**Comment by AndreasVaage** [comment]
After installing the newest version in a clean env it worked.
