### ISSUE TITLE
Installation Error With Latest Version of nbdev followed by nbdev_install_git_hooks

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#64]
I'm running this in a Docker Container to ensure reproduceability:  

I run 
`pip install nbdev`

followed by
`nbdev_install_git_hooks`

And I get the below.  I am able to reproduce this error

```
`Traceback (most recent call last):
  File "/usr/local/bin/nbdev_install_git_hooks", line 8, in <module>
    sys.exit(nbdev_install_git_hooks())
  File "/usr/local/lib/python3.6/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/usr/local/lib/python3.6/site-packages/nbdev/cli.py", line 241, in nbdev_install_git_hooks
    path = Config().config_file.parent
  File "/usr/local/lib/python3.6/site-packages/nbdev/imports.py", line 42, in __init__
    assert self.config_file.exists(), "Use `Config.create` to create a `Config` object the first time"
AssertionError: Use `Config.create` to create a `Config` object the first time
root@4b0f7387a983:/# Config.create
bash: Config.create: command not found
root@4b0f7387a983:/# nbdev_install_git_hooks
Traceback (most recent call last):
  File "/usr/local/bin/nbdev_install_git_hooks", line 8, in <module>
    sys.exit(nbdev_install_git_hooks())
  File "/usr/local/lib/python3.6/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/usr/local/lib/python3.6/site-packages/nbdev/cli.py", line 241, in nbdev_install_git_hooks
    path = Config().config_file.parent
  File "/usr/local/lib/python3.6/site-packages/nbdev/imports.py", line 42, in __init__
    assert self.config_file.exists(), "Use `Config.create` to create a `Config` object the first time"
AssertionError: Use `Config.create` to create a `Config` object the first time```

**Comment by hamelsmu** [comment]
cc: @sgugger

**Comment by sgugger** [comment]
Indeed, it tries to locate the settings.ini file file to know the base directory of the repo. Defaulted to the current path if there is no settings.ini file.

**Comment by hamelsmu** [comment]
Sorry

**Comment by sgugger** [comment]
No problems, it was a bug, not a feature ;)
