### ISSUE TITLE
nbdev_build_docs error not creating HTML 

### ISSUE THREAD

**Issue by saraebell** [fastai/nbdev#643]
I have used the commands nbdev_build_lib and nbdev_build_docs before without any issues however now I am having issues specifically with the command **nbdev_build_docs** to convert to HTML 

I have tried uninstalling and reinstalling nbdev with pip but I continue to get the same error.
As of now I have I have the versions:
nbdev version 1.2.11
Python version 3.9.7
fastcore version 1.5.6

I am still relatively new to coding and with using nbdev so I would appreciate it if someone could look over the code below and provide any additional suggestions or advice to resolve this error. Thank you!

```
(github-nbdev) [014843907@coe-hpc1 tad-boundaries-code]$ nbdev_build_lib
Converted 00_download_data.ipynb.
Converted 01_load_tad_boundaries.ipynb.
Converted 02_load_repeats.ipynb.
Converted 03_load_genes.ipynb.
Converted 04_load_atac.ipynb.
Converted 05_load_ctcf.ipynb.
Converted 10_analysis_segdups_count_tads.ipynb.
Converted 11_analysis_segdups_tads.ipynb.
Converted 12_analysis_segdups_ctcf.ipynb.
Converted 13_analysis_segdups_synthetic_tads.ipynb.
Converted 14_analysis_sedef_synthetic_tads.ipynb.
Converted 15-2_analysis_hg19_sedef_tads_v2.ipynb.
Converted 15_analysis_hg19_sedef_tads.ipynb.
Converted 16_analysis_mm8_sedef_tads.ipynb.
Converted 17_analysis_mm8_biser_tads.ipynb.
Converted 20_visualization.ipynb.
Converted index.ipynb.
(github-nbdev) [014843907@coe-hpc1 tad-boundaries-code]$ nbdev_build_docs
converting: /home/014843907/TADs/tad-boundaries-code/00_download_data.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/03_load_genes.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/index.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/04_load_atac.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/20_visualization.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/01_load_tad_boundaries.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/05_load_ctcf.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/02_load_repeats.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/13_analysis_segdups_synthetic_tads.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/12_analysis_segdups_ctcf.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/11_analysis_segdups_tads.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/16_analysis_mm8_sedef_tads.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/10_analysis_segdups_count_tads.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/15_analysis_hg19_sedef_tads.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/14_analysis_sedef_synthetic_tads.ipynb
converting: /home/014843907/TADs/tad-boundaries-code/17_analysis_mm8_biser_tads.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
converting: /home/014843907/TADs/tad-boundaries-code/15-2_analysis_hg19_sedef_tads_v2.ipynb
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
[Errno 13] Permission denied: '/usr/share/jupyter/conf.json'
Conversion failed on the following:
00_download_data.ipynb
03_load_genes.ipynb
04_load_atac.ipynb
index.ipynb
01_load_tad_boundaries.ipynb
02_load_repeats.ipynb
20_visualization.ipynb
05_load_ctcf.ipynb
13_analysis_segdups_synthetic_tads.ipynb
12_analysis_segdups_ctcf.ipynb
16_analysis_mm8_sedef_tads.ipynb
11_analysis_segdups_tads.ipynb
10_analysis_segdups_count_tads.ipynb
15_analysis_hg19_sedef_tads.ipynb
17_analysis_mm8_biser_tads.ipynb
14_analysis_sedef_synthetic_tads.ipynb
15-2_analysis_hg19_sedef_tads_v2.ipynb
Traceback (most recent call last):
  File "/home/014843907/anaconda3/envs/github-nbdev/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/fastcore/script.py", line 117, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 649, in nbdev_build_docs
    if fname is None: make_sidebar()
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 717, in make_sidebar
    create_default_sidebar()
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 709, in create_default_sidebar
    dic = {get_config().lib_name: _create_default_sidebar()}
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 701, in _create_default_sidebar
    for t,f in groupby(names, _get_title).items():
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/fastcore/basics.py", line 552, in groupby
    for o in x: res.setdefault(key(o), []).append(val(o))
  File "/home/014843907/anaconda3/envs/github-nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 690, in _get_title
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/014843907/TADs/tad-boundaries-code/docs/download_data.html'
(github-nbdev) [014843907@coe-hpc1 tad-boundaries-code]$ 
```

**Comment by jph00** [comment]
Please try forums.fast.ai for help with nbdev setup
