### ISSUE TITLE
`show_doc` renders incorrect class init in notebook, and errors out when calling `nbdev_docs`

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/nbdev#658]
[`LossMetric`](https://github.com/warner-benjamin/fastxtend/blob/main/fastxtend/metrics.py#L777) is rendered by `show_doc` in notebooks incorrectly. The `__init__` has the following arguments:
```python
class LossMetric(AvgMetricX):
    "Create a metric from `loss_func.attr` named `nm`"
    def __init__(self, attr, nm=None, log_metric=LogMetric.Valid, **kwargs):
        super().__init__(noop, log_metric=log_metric, **kwargs)
        store_attr('attr,nm')
```
but in the notebook `show_doc(LossMetric)` renders:
```
class LossMetric[source]
LossMetric(func, to_np=False, invert_arg=False, dim_argmax=None, activation=<ActivationType.No: 1>, thresh=None, log_metric=None, name=None) :: AvgMetricX

Create a metric from loss_func.attr named nm
```
where the arguments `func`, `to_np`, etc are from [`AvgMetricX`](https://github.com/warner-benjamin/fastxtend/blob/main/fastxtend/metrics.py#L95), and `LossMetric`'s `attr` and `nm` are not rendered.

This causes a `KeyError: 'func'` when running `nbdev_docs`, presumably since `LossMetric` doesn't have `func` as an init argument.

```
Error in cell 256:
#| echo: false
show_doc(LossMetric)Traceback (most recent call last):
  File "/miniconda3/envs/py37/bin/nbdev_filter", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_filter')())
  File "site-packages/fastcore/script.py", line 117, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/nbdev/nbdev/cli.py", line 118, in nbdev_filter
    NBProcessor(nb=nb, procs=filt.procs(), preprocs=filt.preprocs(), postprocs=filt.postprocs()).process()
  File "/nbdev/nbdev/process.py", line 158, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/nbdev/nbdev/process.py", line 142, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/nbdev/nbdev/processors.py", line 139, in __call__
    raise self.k.exc[1] from None
  File "/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()
  File "/nbdev/nbdev/showdoc.py", line 135, in _repr_markdown_
    if self.dm.has_docment: doc += f"\n\n{self.dm}"
  File "e/nbdev/nbdev/showdoc.py", line 58, in has_docment
    def has_docment(self): return 'docment' in self._columns and self._row_list 
  File "/nbdev/nbdev/showdoc.py", line 70, in _row_list
    ordered_params = [(p, self.dm[p]) for p in self.params if p != 'self']
  File "/nbdev/nbdev/showdoc.py", line 70, in <listcomp>
    ordered_params = [(p, self.dm[p]) for p in self.params if p != 'self']
KeyError: 'func'
```

**Comment by warner-benjamin** [comment]
This might be related. I think also have `show_doc` failing on `nbdev_docs` while patching. Although the error doesn't state what notebook it occurred in and doesn't seem to list the right cell number.

I think it's failing here in [this notebook](https://github.com/warner-benjamin/fastxtend/blob/main/nbs/vision.augment.itemtensor.ipynb). Except this is cell 9 not 11, and it's not supposed to be exported to docs due to the `#|exporti` flag
```python
#|exporti
@patch
def resize(x:TensorImage|TensorMask, 
    size:int|tuple[int,int], 
    interpolation:Enum
):
```
Error log:
```
Error in cell 11:
#| echo: false
show_doc(['TensorImage.resize', 'TensorMask.resize'])Traceback (most recent call last):
  File "/py37/bin/nbdev_filter", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_filter')())
  File "/python3.7/site-packages/fastcore/script.py", line 117, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/nbdev/nbdev/cli.py", line 118, in nbdev_filter
    NBProcessor(nb=nb, procs=filt.procs(), preprocs=filt.preprocs(), postprocs=filt.postprocs()).process()
  File "/nbdev/nbdev/process.py", line 158, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/nbdev/nbdev/process.py", line 142, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/nbdev/nbdev/processors.py", line 139, in __call__
    raise self.k.exc[1] from None
  File "/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-3915fa0059ac>", line 2, in <module>
  File "/nbdev/nbdev/showdoc.py", line 146, in show_doc
    else:return renderer(sym or show_doc, disp=disp)
  File "/nbdev/nbdev/showdoc.py", line 110, in __init__
    self.sig = None if self.isprop else _signature(sym)
  File "/nbdev/nbdev/showdoc.py", line 24, in _signature
    def _signature(obj): return inspect.signature(obj, eval_str=True) if _ispy3_10() else inspect.signature(obj)
  File "/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/python3.7/inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: ['TensorImage.resize', 'TensorMask.resize'] is not a callable object
```

**Comment by jph00** [comment]
@warner-benjamin I believe the 2nd should be fixed, and the 1st I can't replicate. I've added something very similar in `tests/showdoc_test.ipynb` and it's working OK. If you're still having a problem, could you please open a new issue with a minimal standalone repro? Maybe starting with what's already in showdoc_test.ipynb, if possible.
