### ISSUE TITLE
KeyError: 'repo'

### ISSUE THREAD

**Issue by Python-doctor** [fastai/nbdev#687]
When I try to follow Jeremy's tutorial on starting a new Nbdev project with nbdev_new, I got the following error

`settings.ini` updated with configuration values.
Traceback (most recent call last):
  File "/home/johnyquest/mambaforge/bin/nbdev_new", line 8, in <module>
    sys.exit(nbdev_new())
  File "/home/johnyquest/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/johnyquest/mambaforge/lib/python3.9/site-packages/nbdev/cli.py", line 294, in nbdev_new
    settings = settings.format(**config)
KeyError: 'repo'

**Comment by jph00** [comment]
Please use forums.fast.ai for support
