### ISSUE TITLE
KeyError: 'repo'

### ISSUE THREAD

**Issue by fabge** [fastai/nbdev#720]
When trying to create a new nbdev project with `nbdev_new`, following error is thrown after entering the nbdev configuration parameters:

```bash
Traceback (most recent call last):
  File "/home/fabian/.venv/venv/bin/nbdev_new", line 8, in <module>
    sys.exit(nbdev_new())
  File "/home/fabian/.venv/venv/lib/python3.9/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/fabian/.venv/venv/lib/python3.9/site-packages/nbdev/cli.py", line 296, in nbdev_new
    settings = settings.format(**config)
KeyError: 'repo'
```

I have initialized a new repository with `gh repo create`, so the repo should be extracted via `owner,repo = repo_details(url)` in the `_fetch_from_git` function.

I am using nbdev 2.0.7.

**Comment by jph00** [comment]
Fixed in master. Generally this problem occurs if you have a private repo.
