### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by stuartmarsden** [fastai/nbdev#8]
I just made a test repo and followed the getting started guide.

I can build the modules but I get an error when trying to build the docs

`nbdev_build_docs`

result 

`converting: /home/jovyan/work/testingNBDev/99_index.ipynb
jekyll.tpl
Traceback (most recent call last):
  File "/opt/conda/bin/nbdev_build_docs", line 10, in <module>
    sys.exit(nbdev_build_docs())
  File "/opt/conda/lib/python3.7/site-packages/fastscript/fastscript.py", line 42, in _f
    func(**args.__dict__)
  File "/opt/conda/lib/python3.7/site-packages/nbdev/cli.py", line 148, in nbdev_build_docs
    if mk_readme: make_readme()
  File "/opt/conda/lib/python3.7/site-packages/nbdev/cli.py", line 136, in make_readme
    convert_md(index_fn, Config().config_file.parent, jekyll=False)
  File "/opt/conda/lib/python3.7/site-packages/nbdev/export2html.py", line 401, in convert_md
    f.write(exp.from_notebook_node(nb, resources=meta_jekyll)[0])
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 322, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 114, in template
    self._template_cached = self._load_template()
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 293, in _load_template
    return self.environment.get_template(template_file)
  File "/opt/conda/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/conda/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/conda/lib/python3.7/site-packages/jinja2/loaders.py", line 408, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: md.tpl`

**Comment by dperezrada** [comment]
Same problem here.
It's seems the packaged version it's not including the .tpl files.
Local version seem to work ok
```
git clone https://github.com/fastai/nbdev
cd nbdev
pip install -e .
```

A possible solution for the packeged version could be adding `MANIFEST.in`  with
`include nbdev/templates/*tpl`

**Comment by sgugger** [comment]
Yes, that's exactly the problem. We forgot to add those files in the MANIFEST and didn't realize it as we're only using a developer install. Will fix and release a new version.

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/nbdev/commit/367f69773cda767217faca841d84f1f2fc56df6d). I also made a new release so v0.1.3 should have those files.

**Comment by stuartmarsden** [comment]
Thanks for the quick response.

**Comment by shunkakinoki** [comment]
Appreciate this!
