### ISSUE TITLE
run command nbdev_build_lib got  KeyError: 'copyright'

### ISSUE THREAD

**Issue by openthings** [fastai/nbdev#80]
i am running command nbdev_build_lib, got：
```
:~/openthings/nbdev_template$ nbdev_build_lib
Traceback (most recent call last):
  File "/home/supermap/anaconda3/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/home/supermap/anaconda3/lib/python3.6/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/home/supermap/anaconda3/lib/python3.6/site-packages/nbdev/cli.py", line 21, in nbdev_build_lib
    write_tmpls()
  File "/home/supermap/anaconda3/lib/python3.6/site-packages/nbdev/export2html.py", line 334, in write_tmpls
    write_tmpl(config_tmpl, 'user lib_name title copyright description', cfg, cfg.doc_path/'_config.yml')
  File "/home/supermap/anaconda3/lib/python3.6/site-packages/nbdev/export2html.py", line 326, in write_tmpl
    vs = {o:cfg.d[o] for o in nms.split()}
  File "/home/supermap/anaconda3/lib/python3.6/site-packages/nbdev/export2html.py", line 326, in <dictcomp>
    vs = {o:cfg.d[o] for o in nms.split()}
  File "/home/supermap/anaconda3/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'copyright'
```

add following to setting.ini,success:
```
copyright = openthings
description = test
```

**Comment by KBodolai** [comment]
Hi openthings!

I was following the nbdev tutorial and got virtually the same issue as you had:
```
(nbdev) ➜  nbdev_test git:(master) ✗ nbdev_build_lib
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nbdev/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/site-packages/fastcore/script.py", line 104, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 477, in nbdev_build_lib
    write_tmpls()
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 469, in write_tmpls
    write_tmpl(config_tmpl, 'user lib_name title copyright description', cfg, path/'_config.yml')
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 460, in write_tmpl
    vs = {o:cfg.d[o] for o in nms.split()}
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/site-packages/nbdev/export2html.py", line 460, in <dictcomp>
    vs = {o:cfg.d[o] for o in nms.split()}
  File "/opt/anaconda3/envs/nbdev/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'copyright'
```
I tried your solution in setting.ini, but unfortunately it didn't work for me, right now it looks like this:

```
[DEFAULT]
# All sections below are required unless otherwise specified
host = github
lib_name = nbdev_test
# For Enterprise Git add variable repo_name and company name
# repo_name = analytics
# company_name = nike

user = KBodolai
description = "testing nbdev"
keywords = test
author = myname
author_email = myemail@gmail.com
copyright = Copyrightinfo
```

Any idea of why this happens or how I can fix it?

Thanks!
