### ISSUE TITLE
`nbdev_preview` : nb_fmdict fail in some case

### ISSUE THREAD

**Issue by benoit-cty** [fastai/nbdev#801]
When trying `nbdev_preview` on https://git.leximpact.dev/leximpact/leximpact-prepare-data/-/blob/memo-pepa/notebooks/contributing.ipynb
I get the error:
```py
Preparing to preview
Traceback (most recent call last):
  File "/media/data/dev/src/test_nbdev/.venv/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/media/data/dev/src/test_nbdev/.venv/lib/python3.8/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/media/data/dev/src/test_nbdev/.venv/lib/python3.8/site-packages/nbdev/cli.py", line 127, in nbdev_filter
    with redirect_stdout(dn): filt.nb_proc(nb).process()
  File "/media/data/dev/src/test_nbdev/.venv/lib/python3.8/site-packages/nbdev/process.py", line 128, in process
    self.nb = opt_set(self.nb, proc(self.nb))
  File "/media/data/dev/src/test_nbdev/.venv/lib/python3.8/site-packages/nbdev/processors.py", line 246, in infer_frontmatter
    _fmdict = merge(nb_fmdict(nb), {'output-file': _exp+'.html'} if _exp else {})
  File "/media/data/dev/src/test_nbdev/.venv/lib/python3.8/site-packages/nbdev/processors.py", line 217, in nb_fmdict
    title,desc=_re_title.match(cell.source).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

Replacing this code in processors.py solve it:
```py
def nb_fmdict(nb, remove=True): 
    "Infer the front matter from a notebook's markdown formatting"
    md_cells = _celltyp(nb, 'markdown').filter(_istitle)
    if not md_cells: return {}
    cell = md_cells[0]
    title_match = _re_title.match(cell.source)
    if title_match:
        title,desc=title_match.groups()
        flags = re.findall('^-\s+(.*)', cell.source, flags=re.MULTILINE)
        flags = [s.split(':', 1) for s in flags if ':' in s] if flags else []
        flags = merge({k:v for k,v in flags if k and v}, 
                      {'title':yaml_str(title)}, {'description':yaml_str(desc)} if desc else {})
        if remove: cell['source'] = None
        return yml2dict('\n'.join([f"{k}: {flags[k]}" for k in flags]))
    else: return {}
```

By:
```py
def nb_fmdict(nb, remove=True): 
    "Infer the front matter from a notebook's markdown formatting"
    md_cells = _celltyp(nb, 'markdown').filter(_istitle)
    if not md_cells: return {}
    cell = md_cells[0]
    regex = _re_title.match(cell.source)
    if regex:
        title,desc=regex.groups()
        if title:
            flags = re.findall('^-\s+(.*)', cell.source, flags=re.MULTILINE)
            flags = [s.split(':', 1) for s in flags if ':' in s] if flags else []
            flags = merge({k:v for k,v in flags if k and v}, 
                        {'title':yaml_str(title)}, {'description':yaml_str(desc)} if desc else {})
            if remove: cell['source'] = None
            return flags
    else: return {}
```

So it seems `_istitle` find a title that `_re_title.match` don't find. It's weird because `_istitle` use `_re_title.match`.

Here is the cell that fail:
`[{'cell_type': 'markdown', 'metadata': {}, 'source': '## NBDev\n\n```bash\n# Run pre-commit before converting notebooks\npoetry run pre-commit  run --all-files\n# Build lib from notebook\npoetry run nbdev_build_lib\n# Build docs from notebook\npoetry run nbdev_build_docs\n# Re-run pre-commit\npoetry run pre-commit  run --all-files\n\n```\n', 'idx_': 13, 'directives_': {}}]`

**Comment by hamelsmu** [comment]
Iv'e updated nbdev and I believe this issue is now fixed.  Can you try upgrading with 

pip install -U git+https://github.com/fastai/nbdev.git 

And see if that solves the issue?

**Comment by benoit-cty** [comment]
Yes, solved by update ! Issue closed.
