### ISSUE TITLE
`nbdev_docs` tries to execute code despite `skip_exec`

### ISSUE THREAD

**Issue by deven-gqc** [fastai/nbdev#814]
I am trying to run `nbdev_docs` and the conversion keeping failing on a nb which has
```
#| nbflags skip_exec
import darts
```

```
(nb2) devengqc@17-CN0065CL-1:~/git/projects/ubc$ nbdev_docs
[ 1/13] Hydrotrek_Flow_Path_calculation.ipynb
[ 2/13] bldg_along_wtrmainbreak.ipynb
[ 3/13] geojson_polylines.ipynb
[ 4/13] darts.ipynb
Traceback (most recent call last):
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-f5d9044e7f0c>", line 1, in <cell line: 1>
ModuleNotFoundError: No module named 'darts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/devengqc/mambaforge/envs/nb2/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/nbdev/cli.py", line 127, in nbdev_filter
    with redirect_stdout(dn): filt.nb_proc(nb).process()
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/nbdev/process.py", line 130, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/nbdev/process.py", line 111, in _process_cell
    cell = opt_set(cell, proc(cell))
  File "/home/devengqc/mambaforge/envs/nb2/lib/python3.9/site-packages/nbdev/processors.py", line 298, in __call__
    if self.k.exc: raise Exception(f'Error: cell {cell.idx_}:\n{cell.source}') from self.k.exc[1]
Exception: Error: cell 4:
import darts
```

**Comment by jph00** [comment]
We've recently made a change to move away from `nbflags` to instead just using YAML frontmatter . Create a raw cell (preferably at the top of your NB) containing:

```
---
skip_exec: true
---
```
