### ISSUE TITLE
Tutorial: nbdev-hello-world deploy to GitHub Pages action failing

### ISSUE THREAD

**Issue by decherd** [fastai/nbdev#837]
I'm following along with the tutorial and on the initial commit I'm getting a failed action for deploying to GitHub Pages. Here is the log:

Unpacking quarto (1.0.38) ...
[209](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:221)
Setting up quarto (1.0.38) ...
[210](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:222)
Traceback (most recent call last):
[211](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:223)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/nbdev_filter", line 8, in <module>
[212](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:224)
    sys.exit(nbdev_filter())
[213](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:225)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/fastcore/script.py", line 116, in _f
[214](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:226)
    return tfunc(**merge(args, args_from_prog(func, xtra)))
[215](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:227)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/cli.py", line 127, in nbdev_filter
[216](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:228)
    with redirect_stdout(dn): filt.nb_proc(nb).process()
[217](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:229)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/process.py", line 130, in process
[218](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:230)
    for cell in self.nb.cells: self._process_cell(cell)
[219](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:231)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/process.py", line 111, in _process_cell
[220](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:232)
    cell = opt_set(cell, proc(cell))
[221](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:233)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/processors.py", line 194, in add_links
[222](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:234)
    nl = NbdevLookup()
[223](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:235)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/doclinks.py", line 167, in __init__
[224](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:236)
    self.entries = {o.name: o.load() for o in pkg_resources.iter_entry_points(group='nbdev')
[225](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:237)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/doclinks.py", line 167, in <dictcomp>
[226](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:238)
    self.entries = {o.name: o.load() for o in pkg_resources.iter_entry_points(group='nbdev')
[227](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:239)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in load
[228](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:240)
    return self.resolve()
[229](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:241)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2477, in resolve
[230](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:242)
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
[231](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:243)
ModuleNotFoundError: No module named 'nbdev_hello_world'
[232](https://github.com/decherd/nbdev-hello-world/runs/7798398132?check_suite_focus=true#step:2:244)
Error: Process completed with exit code 1.

The first time it was happening I had underscores in the name but deleted that repo and started over and am still gettin this same ModuleNotFoundError.

**Comment by decherd** [comment]
Yes, that did it. I figured there was something missing in the tutorial as it seemed simpler than the 90min Youtube tutorial you have. Thanks.
