### ISSUE TITLE
Error while following the end-to-end tutorial of nbdev

### ISSUE THREAD

**Issue by gualbe** [fastai/nbdev#904]
I got an error following the end-to-end tutorial at [https://nbdev.fast.ai/tutorial.html](https://nbdev.fast.ai/tutorial.html).

The error occurs between the steps:

- [Install your package](https://nbdev.fast.ai/tutorial.html#install-your-package)
- [Preview your docs](https://nbdev.fast.ai/tutorial.html#preview-your-docs)

When I run **nbdev_preview** I got this error:

`Preparing to preview
Traceback (most recent call last):
  File "/Users/gualberto/miniforge3/envs/experimental/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/cli.py", line 127, in nbdev_filter
    with redirect_stdout(dn): filt.nb_proc(nb).process()
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/process.py", line 130, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/process.py", line 111, in _process_cell
    cell = opt_set(cell, proc(cell))
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/processors.py", line 194, in add_links
    nl = NbdevLookup()
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/doclinks.py", line 167, in __init__
    self.entries = {o.name: o.load() for o in pkg_resources.iter_entry_points(group='nbdev')
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/nbdev/doclinks.py", line 167, in <dictcomp>
    self.entries = {o.name: o.load() for o in pkg_resources.iter_entry_points(group='nbdev')
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/Users/gualberto/miniforge3/envs/experimental/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'nbdev_hello_world'`

It seems that the package proposed to build in the tutorial is not installed properly using:

> pip install -e '.[dev]'

The output was:

`Obtaining file:///Users/_____/.../nbdev-hello-world
  Preparing metadata (setup.py) ... done
Installing collected packages: nbdev-hello-world
  Running setup.py develop for nbdev-hello-world
Successfully installed nbdev-hello-world-0.0.1`

However, if I try to import such package from a Python interpreter I got the same:

> ModuleNotFoundError: No module named 'nbdev_hello_world'`

I also tried with other project names by replacing "-" to "\_" and removing both all "-" and "\_".

I can't continue the tutorial due to the error in this step.

Thank you very much in advance for your time.

**Comment by seeM** [comment]
Could you please share a link to the repo? That’s the easiest way to figure out what’s going wrong

**Comment by gualbe** [comment]
> Could you please share a link to the repo? That’s the easiest way to figure out what’s going wrong

Hello! Sure, I have tried with three different repos:

- [https://github.com/gualbe/nbdev-hello-world](https://github.com/gualbe/nbdev-hello-world)
- [https://github.com/gualbe/nbdev_hello](https://github.com/gualbe/nbdev_hello)
- [https://github.com/gualbe/nbdevhello](https://github.com/gualbe/nbdevhello)

Thank you very much,

**Comment by seeM** [comment]
Thank you @gualbe! Are you sure you're on the latest version of nbdev? We made significant improvements to `nbdev_new` recently that I suspect caused this issue. You can upgrade with:

```sh
pip install --upgrade nbdev
```

**Comment by seeM** [comment]
Great, let me know if it works :) I'll close this so long and re-open if you're still having issues
