### ISSUE TITLE
unable to make release

### ISSUE THREAD

**Issue by deven367** [fastai/nbdev#907]
I'm trying to make a release for my package, and it gives a `fastcore.basics.HTTP404NotFoundError`

I am on the latest versions of `nbdev` and `fastcore`. 
`nbdev` version: 2.2.5
`fastcore` version: 1.5.21
```
(base) deven@Ideapad-310:~/projects/clean_plot$ nbdev_release_gh
Make release now? (y/n) y
Traceback (most recent call last):
  File "/home/deven/mambaforge/bin/nbdev_release_gh", line 8, in <module>
    sys.exit(release_gh())
  File "/home/deven/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 117, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/deven/mambaforge/lib/python3.9/site-packages/nbdev/release.py", line 132, in release_gh
    ver = Release(token=token).release()
  File "/home/deven/mambaforge/lib/python3.9/site-packages/nbdev/release.py", line 89, in release
    self.gh.create_release(ver, branch=self.cfg.branch, body=notes)
  File "/home/deven/mambaforge/lib/python3.9/site-packages/ghapi/core.py", line 176, in create_release
    rel = self.repos.create_release(tag_name, target_commitish=branch, name=name, body=body,
  File "/home/deven/mambaforge/lib/python3.9/site-packages/ghapi/core.py", line 61, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/home/deven/mambaforge/lib/python3.9/site-packages/ghapi/core.py", line 111, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/home/deven/mambaforge/lib/python3.9/site-packages/fastcore/net.py", line 214, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/home/deven/mambaforge/lib/python3.9/site-packages/fastcore/net.py", line 115, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
fastcore.basics.HTTP404NotFoundError: HTTP Error 404: Not Found
```

**Comment by jph00** [comment]
Generally this means you haven't set GITHUB_TOKEN. I've just released a new version of `ghapi` which will warn you in this situation. Without your token set, GitHub isn't authenticated, so you can't create a release.
