### ISSUE TITLE
`AnnAssign` object has no attribute 'targets'

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#953]
looks like it's a pure internal reference being wrong? I don't see any of my code being mentioned:

```bash
❯ nbdev_export
Traceback (most recent call last):
  File "/luna9/maye/mambaforge/envs/py310/bin/nbdev_export", line 10, in <module>
    sys.exit(nbdev_export())
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/script.py", line 117, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/doclinks.py", line 124, in nbdev_export
    for f in files: nb_export(f)
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/export.py", line 59, in nb_export
    mm.make(cells, all_cells, lib_path=lib_path)
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/maker.py", line 193, in make
    _all = self.make_all(all_cells)
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/maker.py", line 108, in make_all
    return retr_exports(L(cells).map(NbCell.parsed_).concat())
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/maker.py", line 95, in retr_exports
    all_assigns = assigns.filter(lambda o: getattr(o.targets[0],'id',None)=='_all_')
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/foundation.py", line 160, in filter
    return self._new(filter_ex(self, f=f, negate=negate, gen=gen, **kwargs))
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/basics.py", line 637, in filter_ex
    return list(res)
  File "/luna9/maye/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/maker.py", line 95, in <lambda>
    all_assigns = assigns.filter(lambda o: getattr(o.targets[0],'id',None)=='_all_')
AttributeError: 'AnnAssign' object has no attribute 'targets'. Did you mean: 'target'?
```

## version info

```bash
❯ mamba list nbdev
# packages in environment at /luna9/maye/mambaforge/envs/py310:
#
# Name                    Version                   Build  Channel
nbdev                     2.2.8                      py_0    fastai
```
Fastcore is at 1.5.22

**Comment by jph00** [comment]
It's having trouble parsing/understanding your code. Is this a public repo I could look at?

**Comment by jph00** [comment]
n/m I see what the problem is. Will fix now.

**Comment by michaelaye** [comment]
i think this line needs that fix as well?

https://github.com/fastai/nbdev/blob/d351adc34cf36ac9efc2034b5092eeab8bd20ca6/nbdev/maker.py#L181

I can PR.

**Comment by jalew188** [comment]
Thanks @michaelaye . Line 181 should also be changed otherwise it does not work for my code
