### ISSUE TITLE
nbdev_preview errors out

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#971]
`nbdev_preview` fails in 2.2.7, 2.2.8 and HEAD like so:

```bash
…/nbplanetary ❯ nbdev_preview
Traceback (most recent call last):
  File "/home/ayek72/mambaforge/envs/py310/bin/nbdev_preview", line 10, in <module>
    sys.exit(preview())
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/ayek72/mambaforge/envs/py310/lib/python3.10/site-packages/nbdev/quarto.py", line 278, in preview
    nbdev_quarto.__wrapped__(path, preview=True, **kwargs)
TypeError: nbdev.quarto.nbdev_quarto() got multiple values for keyword argument 'preview'
```

## version infos

I tried with nbdev 2.2.7, 2.2.8, and HEAD (57f7e5b020e08f875f389010accf5cc38af26bde)

```bash
…/nbplanetary ❯ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.1.168
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6 (Conda)
      Path: /home/ayek72/mambaforge/envs/py310/bin/python
      Jupyter: 4.11.1
      Kernels: python3, xonsh

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
```bash
…/nbdev ❯ uname -a
Linux x.x.x.x 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by michaelaye** [comment]
If i remove `preview=True` here, `nbdev_preview` works again. Bad fix or ok?


https://github.com/fastai/nbdev/blob/master/nbdev/quarto.py#L278

**Comment by jph00** [comment]
Should be fixed now.
