### ISSUE TITLE
Pre-save hook failed

### ISSUE THREAD

**Issue by tttiago** [fastai/nbdev#992]
I installed nbdev on my conda base environment, from the fastai anaconda channel and then run ```nbdev_install_hooks``` and got the "Hooks are installed." message.

When  I opened JupyterLab and saved a notebook, my terminal shows the following message
> Pre-save hook failed on Gravity Spy/Untitled1.ipynb
    Traceback (most recent call last):
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 134, in run_pre_save_hook
        self.pre_save_hook(model=model, path=path, contents_manager=self, **kwargs)
      File "/home/tiago/.jupyter/jupyter_server_config.py", line 4, in nbdev_clean_jupyter
        clean_jupyter(**kwargs)
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/nbdev/clean.py", line 144, in clean_jupyter
        jupyter_hooks = get_config(path=path).jupyter_hooks
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/fastcore/foundation.py", line 269, in __getattr__
        def __getattr__(self,k):   return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/fastcore/basics.py", line 216, in stop
        raise e
    AttributeError: jupyter_hooks

Am I missing something?

**Comment by seeM** [comment]
This is fixed by https://github.com/fastai/fastcore/pull/482. In the mean time, you can also fix it by explicitly including `jupyter_hooks = True` in your `settings.ini` file (in the root of your repo)

**Comment by tttiago** [comment]
Thank you for your response! I had no such file so I created a ```settings.ini``` file with ```jupyter_hooks = True```.
I got an error about a missing header in the file so I added ```[DEFAULT]``` at the top.
Still, I get a similar error
> Pre-save hook failed on Gravity Spy/00_dset_creation.ipynb
    Traceback (most recent call last):
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 134, in run_pre_save_hook
        self.pre_save_hook(model=model, path=path, contents_manager=self, **kwargs)
      File "/home/tiago/.jupyter/jupyter_server_config.py", line 4, in nbdev_clean_jupyter
        clean_jupyter(**kwargs)
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/nbdev/clean.py", line 145, in clean_jupyter
        if jupyter_hooks: _nbdev_clean(model['content'], path=path)
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/nbdev/clean.py", line 118, in _nbdev_clean
        clean_ids = cfg.clean_ids
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/fastcore/foundation.py", line 269, in __getattr__
        def __getattr__(self,k):   return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
      File "/home/tiago/anaconda3/lib/python3.9/site-packages/fastcore/basics.py", line 216, in stop
        raise e
    AttributeError: clean_ids

Have I done something wrong with the settings.ini file? 
Also, do I need to have this file in each repo I use nbdev hooks?

**Comment by seeM** [comment]
Sorry about that! It’s a bug in the latest version of fastcore (a dependency of nbdev). We’ve made a fix but it still needs to be released. A better workaround until then might be to downgrade fastcore to 1.5.22

You shouldn’t need a settings.ini file at all, it was my attempt at a workaround until the fix mentioned above was released

**Comment by tttiago** [comment]
Thank you for the quick response! I downgraded fastcore to 1.5.22 and conda also downgraded nbdev to version 2.2.8. 
Now it works like a charm!

**Comment by black-puppydog** [comment]
I'm so glad I didn't try this yesterday. Thanks @seeM and team for the quick responses, this tool is amazing!

I can confirm that `pip install --upgrade 'fastcore==1.5.22' 'nbdev==2.2.8'` works as a stop-gap! :)

**Comment by seeM** [comment]
😄 now fixed in version [1.5.25](https://github.com/fastai/fastcore/releases/tag/1.5.25)
